

<div class="col-sm-12">
	<?php

		 if((isset($this->view->pedidos)) && (is_array($this->view->pedidos))){

	?>
	<div class="row">
		<div class="col">
			<h3 class="text-warning">Pedidos: <?=$this->view->pessoa->getNomePessoa();?></h3>
		</div>
	</div>
	<div class="row">
		<div class="col" align="center">
			<table class="table table-light table-hover">
				<thead>
					<tr>
						<th>Nº Pedido</th>
						<th>DT. Pedido</th>
						<th>Vendedor</th>
						<th>VL. Frete</th>
						<th>NF</th>
						<th>Tot. Desconto</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<?php
						for ($i=0; !($i == count($this->view->pedidos)) ; $i++) { 
							
					?>
						<tr>
							<td><?=$this->view->pedidos[$i]->idPedido;?></td>
							<td><?=$this->view->pedidos[$i]->dtPedido;?></td>
							<td><?=$this->view->pedidos[$i]->vendedor;?></td>
							<td><?=number_format($this->view->pedidos[$i]->frete, 2, ',', '.');?></td>
							<td>-</td>
							<td><?=number_format($this->view->pedidos[$i]->totalDesconto, 2, ',', '.');?></td>
							<td><?=number_format($this->view->pedidos[$i]->total, 2, ',', '.');?></td>
						</tr>

					<?php

						}
					?>
				</tbody>
			</table>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		</div>
	</div>
	<?php

		}else{

	?>
		<h2 class="alert alert-warning" align="center">Nenhum registro encontrado!</h2>

	<?php	

		}
	?>
</div>