<div class="row" style="background-color: #fff; width: 100%;" align="left">
	<div class="col-md-12 py-4 px-4" style="margin: auto;" id="enderecos-pessoa">
		<div class="row mb-2"><div class="col" id="msg-endereco"></div></div>
		<div class="row">
			<div class="col" align="center"><h2><strong>Seus endereços</strong></h2></div>
		</div>
		<?php
			if($this->view->pessoa->logradouro() == false){

		?>
		<div class="row">
			<div class="col alert alert-warning" align="center">
				<h4>Não exitem endereços cadastrados!</h4>
			</div>
		</div>
		<div class="row">
			<div class="col" align="center">
				<a href="/logradouro/cadastrar" class="btn btn-sm btn-primary" id="new-enderecdo">Adicionar endereço</a>
			</div>
		</div>
		<?php

			}else{
		?>
		<div class="row">
			<?php
			
	    		for ($i=0, $registros = $this->view->pessoa->logradouro(); !($i == count($registros)); $i++) { 
	    			for ($j=0, $logradouro = $registros[$i]->getLogradouro(); !($j == count($logradouro) ); $j++) { 
	    				
	    	?>
	    		<div class="col-md-4 col-sm-12 py-3 " style="border: 4px dotted #ddd; margin: auto;">
					<p><strong>Endereco: </strong><?=$logradouro[$j]->getEndereco()?></p>
					<p><strong>Bairro: </strong><?=$logradouro[$j]->getBairro()?></p>
					<p><strong>Cidade: </strong><?=$logradouro[$j]->getCidade()->getNome()?></p>
					<p><strong>Estado: </strong>MA</p>
					<p><strong>Cep: </strong><?=$logradouro[$j]->getCep()?></p>
					<p><strong>Complemento: </strong><?=$logradouro[$j]->getComplemento()?></p>
					<p><strong>País / Região: </strong>Brasil</p>
					<p><a href="/logradouro/editar?cd=<?=$logradouro[$j]->getIdLogradouro()?>" id="endereco-editar" class="btn btn-sm btn-success" style="background-color: #9400D3">Editar</a></p>
				</div>	
				
			<?php
			
	    			}
	    		}
	    		
		    ?>	
		</div>
		
		<div class="row" align="right">
			<div class="col">
				<a href="/logradouro/cadastrar" class="btn btn-sm btn-primary" id="other-endereco">Adicionar</a>
			</div>
		</div>
		<?php 
			}
		?>
	</div>
</div>