<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<form method="post" class="was-validated" action="/marca/salvar" enctype="multipart/form-data" style="" id="cadastrarMarca">
			<fieldset class=""><legend><strong>Cadastrar Marca</strong></legend>
				<div class="row">
					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idNomeMarca">Nome</label>
									<input type="text" name="nome" id="idNomeMarca" class="form-control" placeholder="Nome do produto" required="required">
								</div>
							</div>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-lg  btn-primary">Cadastrar</button> <a href="/produto/all" class="btn link btn-lg ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>
	</div>
</div>