-- MySQL Script generated by MySQL Workbench
-- ter 10 mar 2020 15:21:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL COMMENT '		',
  `nomeFornecedor` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Logradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Logradouro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Logradouro` (
  `idLogradouro` INT NOT NULL,
  `tipo` ENUM('rua', 'quadra', 'avenida') NULL,
  `cep` VARCHAR(10) NULL,
  `endereco` VARCHAR(200) NULL,
  `complemento` VARCHAR(45) NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idLogradouro`, `Fornecedor_idFornecedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `nomeCliente` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `dtNascimento` DATE NULL,
  `Logradouro_idLogradouro` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Logradouro_idLogradouro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT '							',
  `nomeProduto` VARCHAR(50) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `estoque` INT NULL COMMENT '	',
  `textoPromorcional` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = MyISAM;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UF` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UF` (
  `idUF` INT NOT NULL,
  `País` VARCHAR(45) NULL,
  PRIMARY KEY (`idUF`, `País`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cidade` (
  `idCidade` INT NOT NULL,
  `nomeCidade` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  `UF_idUF` INT NOT NULL,
  `UF_País` VARCHAR(45) NOT NULL,
  `Logradouro_idLogradouro` INT NOT NULL,
  PRIMARY KEY (`idCidade`, `UF_idUF`, `UF_País`, `Logradouro_idLogradouro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Compra` (
  `Cliente_idCliente` INT NOT NULL COMMENT '	',
  `Produto_idProduto` INT NOT NULL,
  `dataCompra` DATE NULL,
  `valorCompra` DECIMAL(15,2) NULL,
  `desconto` DECIMAL(15,2) NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Produto_idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Fornecimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecimento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecimento` (
  `Produto_idProduto` INT NOT NULL COMMENT '								',
  `Fornecedor_idFornecedor` INT NOT NULL,
  `dataFornecimento` DATETIME NULL,
  `qtdFornecida` INT NULL,
  `valorUnitario` DECIMAL(15,2) NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
