-- MySQL Script generated by MySQL Workbench
-- qua 11 mar 2020 15:06:22 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL COMMENT '		',
  `nomeFornecedor` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logradouro` (
  `idLogradouro` INT NOT NULL,
  `tipo` ENUM('rua', 'quadra', 'avenida') NULL,
  `cep` VARCHAR(10) NULL,
  `endereco` VARCHAR(200) NULL,
  `complemento` VARCHAR(45) NULL,
  `Fornecedor_idFornecedor` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nomeCliente` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `dtNascimento` DATE NULL,
  `Logradouro_idLogradouro` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT '							',
  `nomeProduto` VARCHAR(50) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `estoque` INT NULL COMMENT '	',
  `textoPromorcional` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `idUF` INT NOT NULL,
  `País` VARCHAR(45) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `idCidade` INT NOT NULL,
  `nomeCidade` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  `UF_idUF` INT NOT NULL,
  `UF_País` VARCHAR(45) NOT NULL,
  `Logradouro_idLogradouro` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `Cliente_idCliente` INT NOT NULL COMMENT '	',
  `Produto_idProduto` INT NOT NULL,
  `dataCompra` DATE NULL,
  `valorCompra` DECIMAL(15,2) NULL,
  `desconto` DECIMAL(15,2) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecimento` (
  `Produto_idProduto` INT NOT NULL COMMENT '								',
  `Fornecedor_idFornecedor` INT NOT NULL,
  `dataFornecimento` DATETIME NULL,
  `qtdFornecida` INT NULL,
  `valorUnitario` DECIMAL(15,2) NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
