
<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-1">
					<button type="button" class="btn btn-success mt-2" id="controlNavPanel">
						<i class="fas fa-minus" id="ic"></i>
					</button>
				</div>
				<div class="col-md-11">
					<nav class="navbar navbar-expand-sm justify-content-center pt-2 pb-2 pl-2 pr-2" id="navPanelCliente">
					  <ul class="navbar-nav" >
					  	<li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Inico</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Pedidos</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Prevendas</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Orçamentos</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Cadastro</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Ultimas compras</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Nf's</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Info. financeiras</a>
					    </li>
					    <li class="nav-item dropdown" style="margin: auto;">
					      <a class="dropdown-toggle link btn" href="#" id="navbardrop" data-toggle="dropdown">
					        Dropdown link
					      </a>
					      <div class="dropdown-menu" herf="#navbardrop" >
					        <a class="dropdown-item" href="#">Link 1</a>
					        <a class="dropdown-item" href="#">Link 2</a>
					        <a class="dropdown-item" href="#">Link 3</a>
					      </div>
					    </li>
					  </ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row" style="padding: 20px 40px;">
	<div class="col-md-8" style="border-right: 2px solid #ccc">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="vendaPainelTable">
			<fieldset class=""><legend><strong>Pedido:</strong></legend>
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-4">
								<span><strong>Cliente: </strong><br> <?=$this->view->pessoa?></span>
								<input type="hidden" name="cliente" value="<?=$this->view->idCliente?>">
							</div>
							<div class="col-md-2">
								<span><strong>CPF: </strong> 61254689611</span>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label id="entregaLog"><strong>Endereço entrega: </strong></label>
									<select class="form-control" name="entrega">
										<?php
											for ($i=0; !($i == count($this->view->resultLogPessoa)) ; $i++) { 
												
										 ?>
											<option value="<?=$this->view->resultLogPessoa[$i]->getIdLogradouro()?>">
												<?=$this->view->resultLogPessoa[$i]->getEndereco().' - '.$this->view->resultLogPessoa[$i]->getComplemento();?>
											</option>

										<?php
											 }

										?>

									</select>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-12" style="height: 380px;  overflow: auto;">
								<table class="table table-light table-hover mb-2" id="itensTable">
									<thead>
										<tr>
									        <th>Pdoduto</th>
									        <th>Qtd</th>
									        <th>Peço</th>
									        <th>Desconto</th>
									        <th>Total deconto</th>
									        <th>Peço com desconto</th>
									        <th>Subtotal</th>
									        <th>Ação</th>
									    </tr>
								    </thead>
								    <tbody>
								    	<tr id="trMsg">
								    		<td colspan="8">
								    			<div class="container-fluid">
									    			<div class="row" style="">
									    				<div class="col-md-12 alert alert-warning">
									    					<h3 align="center">Adicione produtos para começar!</h3>
									    				</div>
									    			</div>
								    			</div>
								    		</td>
								    	</tr>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group mt-2">
											<label for=""><strong>Formas de pagamento: </strong></label><br>
											<button type="button" data-toggle="modal"  data-target="#myModal" class="btn btn-success cob" id="1">CCR</button>
											<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success cob" id="2">DIN</button>
											<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success cob" id="3">CD</button>
											<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success cob" id="4">BOL</button>
											<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success cob" id="5">NP</button>
											<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-success cob" id="6">CDC</button>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col">
										<div class="form-group">
											<label for="orcamento">Orçamento:</label>
											<input type="radio" name="tipo" id="orcamento" value="1" required="required">
											<label for="prevenda" class="mx-2">Prevenda:</label>
											<input type="radio" name="tipo" id="prevenda" value="2" required="required">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<strong>Total geral: R$ <span id="totGeralVenda" ></span> </strong>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<button id="idFilanizar" type="submit" class="btn btn-primary"  data-toggle="modal" data-target="#myModal">Finalizar</button>
										<a href="/pedido/novo"class="btn btn-danger link">Cancelar</a>
									</div>
								</div>
							</div>
							<div class="col">
								<table class="table table-light table-hover mb-2" id="cobranca">
									<thead>
										<tr>
									        <th>Cob.</th>
									        <th>Val.</th>
									        <th>Qtd parcelas</th>
									        <th>Ação</th>
									    </tr>
								    </thead>
								    <tbody>
								    	<tr id="mgCob">
								    		<td colspan="8">
								    			<div class="container-fluid">
									    			<div class="row" style="">
									    				<div class="col-md-12 alert alert-warning">
									    					<h3 align="center">Adicione formas de pagamento!</h3>
									    				</div>
									    			</div>
								    			</div>
								    		</td>
								    	</tr>
								    </tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	<div class="col-md-4">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="serchProd">
			<fieldset class=""><legend><strong>Buscar produto:</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="loadCodProd"><strong>Cod:</strong></label>
									<input  type="text" name="loadCodProd" id="loadCodProd" class="form-control">
								</div>
							</div>
							<div class="col-md-8">
								<div class="form-group">
									<label for="loadProduto"><strong>Produto:</strong></label>
									<input  type="text" name="loadProduto" id="loadProduto" class="form-control" placeholder="Nome do produto">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<table class="table table-light table-hover" id="tableSearch">
									<thead>
										<tr>
											<th>Cod</th>
									        <th>Produto</th>
									        <th>Preço</th>
									        <th>Estoque</th>
									    </tr>
								    </thead>
								    <tbody>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label for="qtdProduct"><strong>Quantidade:</strong></label>
									<input type="number" name="qtdProduct" id="qtdProduct" class="form-control" >
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="descPercent"><strong>Desconto %:</strong></label>
									<input type="text" name="descPercent" id="descPercent" class="form-control" >
								</div>
							</div>
						</div>
					</div>
				</div>
				<button id="idAdicionar" class="btn btn-primary">Adicionar</button>
			</fieldset>
		</form>
	</div>
</div>