<div class="container-fluid">
	<div class="row" style="width: 82%; margin:auto;padding: 10px 0px;">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12">
					<nav style="background-color: #9400D3" class="navbar navbar-expand-sm justify-content-center pt-2 pb-2 pl-2 pr-2" id="navPanelUser">
					  <ul class="navbar-nav" >
					  	<li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Inico</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Monitora pedo</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="/pessoa/compras" id="ultCompras">Ultimas compras</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Nf's</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Info. financeiras</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Cadastro</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="/chate/init" id="chate">Chat</a>
					    </li>
					  </ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
	<div class="row" style="width: 80.2%; margin:auto auto 4px auto;" align="center">
		<div class="col" id="responseUser" style="background:#ccc; padding: 20px 20px;">
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		</div>
	</div>
</div>
