<div class="container-fluid">
	<div class="row" style="width: 80%; margin:auto;">
		<div class="col-md-12"  style="padding: 20px 40px;">
			<div class="row">
				<div class="col-md-11">
					<nav style="background-color: #9400D3" class="navbar navbar-expand-sm justify-content-center pt-2 pb-2 pl-2 pr-2" id="navPanelUser">
					  <ul class="navbar-nav" >
					  	<li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Inico</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Monitora pedo</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Ultimas compras</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Nf's</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Info. financeiras</a>
					    </li>
					    <li class="nav-item" style="margin: auto;">
					      <a class="pt-2 pb-2 pl-2 pr-2 btn" href="#">Cadastro</a>
					    </li>
					  </ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
			<br/>
		</div>
	</div>
</div>
