<div class="container-fluid">
	<div class="row" style="width: 100%; margin:auto;padding: 10px 0px;">
		<div class="col"><h2>Sua conta</h2></div>
	</div>
	<div class="row" style="width: 100%; margin:auto;padding: 10px 0px;">
		<div class="col-md-5 col-sm-12">
			<nav id="navPanelUser">
				<div class="col-md-12 col-sm-12">
					<div class="row">
						<div class="col-md-6 mb-2 col-sm-12" style="">
							<a class="" href="/pessoa/compras" id="ultCompras">
								<div class="row">
									<div class="col-md-4">
										<img src="files/imagens/painel_cliente/pedido.jpeg" style="width: 100%;height: 100%;"/>
									</div>	
									<div class="col-md-8">
										<p class="h4">Seus pedidos</p>
										<p>Rastrear, devolver</p>
									</div>	
								</div>
							</a>
						</div>
						<div class="col-md-6 mb-2 col-sm-12">
							<a class="" href="/pessoa/cadastro" id="cadastro">
								<div class="row">
									<div class="col-md-4">
										<img src="files/imagens/painel_cliente/acesso_seguranca.jpeg" style="width: 100%;height: 100%;"/>
									</div>	
									<div class="col-md-8">
										<p class="h4">Acesso e segurança</p>
										<p>Alterar o login, nome ou celular</p>
									</div>	
								</div>
							</a>
						</div>
						<div class="col-md-6 mb-2 col-sm-12">
							 <a class="" href="/pessoa/endereco" id="endereco">
								<div class="row">
									<div class="col-md-4">
										<img src="files/imagens/painel_cliente/endereco.jpeg" style="width: 100%;height: 100%;"/>
									</div>	
									<div class="col-md-8">
										<p class="h4">Endereços</p>
										<p>Alterar endereços para pedidos</p>
									</div>	
								</div>
							</a>
						</div>
						<div class="col-md-6 mb-2 col-sm-12">
							<a class="" href="/pessoa/pagamento" id="pagamento">
							<div class="row">
								<div class="col-md-4">
									<img src="files/imagens/painel_cliente/pagamento.jpeg" style="width: 100%;height: 100%;"/>
								</div>	
								<div class="col-md-8">
									<p class="h4">Pagamentos</p>
									<p>Gerenciar formas e configurações de pagamento</p>
								</div>	
							</div>
							</a>
						</div>
						<div class="col-md-6 mb-2 col-sm-12">
							 <a class="" href="/chate/init" id="chate">
								<div class="row">
									<div class="col-md-4">
										<img src="files/imagens/painel_cliente/chate.jpeg" style="width: 100%;height: 100%;"/>
									</div>	
									<div class="col-md-8">
										<p class="h4">Chat</p>
										<p>Fale conosco através do chat</p>
									</div>	
								</div>
							</a>
						</div>
					</div>
				</div>
			</nav>
		</div>
		<div class="col-md-7 col-sm-12" style="background: rgba(220, 220, 220, .3); padding: 20px 20px;">
			<div class="row" id="msg-response" style="width: 100%; margin: auto;">
			</div>
			<div class="row mt-2" style="width:100%; margin:auto auto 4px auto;" align="center">
				<div class="col" id="responseUser" >
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
					<br/>
				</div>
			</div>
		</div>
		</div>
		
	</div>
</div>

