<div class="container-fluid mb-5"><br>
  <div class="row pt-5">
    <div class="col">
      <div class="row">
        <div class="col-sm-6">          
          <h2><strong>Comparativos</strong></h2>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <form action="#" method="post" class="form-horizontal">
        <div class="row">
          <div class="form-group col">
            <label for="inicio">Inico</label>
            <input id="inicio" type="date" name="inico" class="form-control  form-control-sm">
          </div>
          <div class="form-group col">
            <label for="fim">Fim</label>
            <input id="fim" type="date" name="fim" class="form-control form-control-sm">
          </div>
          <div class="form-group col" align="bottom"><br>
             <button type="submit" class="btn btn-sm btn-primary mt-2" style="">Buscar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<div class="card alert alert-secondary mb-4 grafic">
        <div class="card-body">
        	<div class="row">
            <div class="col" align="center">
            	<div class="titleChar h3 text-dark"><strong>Mais vendidos</strong></div>
            </div>
          </div>
          <div class="row">
            <div class="col" align="center">
             <div style="">
                <canvas id="maisVendidos"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
		</div>
		<div class="col-md-6 col-sm-12">
			<div class="card alert alert-secondary grafic">
          <div class="card-body">
          	<div class="row">
              <div class="col" align="center">
              	<div class="titleChar h3 text-dark"><strong>Composição da margem</strong></div>
              </div>
            </div>
            <div class="row">
              <div class="col" align="center">
                <div style="">
                  <canvas id="compMargemLucr"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
		</div>
		<div class="col-md-6 col-sm-12">
			<div class="card alert alert-secondary grafic">
        <div class="card-body">
        	<div class="row">
            <div class="col" align="center">
            	<div class="titleChar h3 text-dark"><strong>Exercicio anual</strong></div>
            </div>
          </div>
          <div class="row">
            <div class="col" align="center">
              <div style="">
                <canvas id="excAnual"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
		</div>
		<div class="col-md-6 col-sm-12">
			<div class="card alert alert-secondary grafic">
        <div class="card-body">
        	<div class="row">
            <div class="col" align="center">
            	<div class="titleChar h3 text-dark"><strong>Meta</strong></div>
            </div>
          </div>
          <div class="row">
            <div class="col" align="center">
              <div>
               <canvas id="metaVenda"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
		</div>
	</div>
</div>