<div class="row ml-3 mb-2" style=" background-color: #fff;padding: 5px;" >
    <div class="col">
    	<div class="row">
        <div class="col pt-2">
          <h4 align="center">Estoque</h4>
          <?php
            if(isset($this->view->resultMonitEst) && (count($this->view->resultMonitEst) > 0)){


          ?>
            <div class="row">
              <div class="col">
                <h5 class="text-dark"><strong>Total itens com estoque baixo:</strong> <?=$this->view->resultMonitEst['qtdItens']?></h5>
              </div>
            </div>
            <div class="row" style="height: 200px; overflow-y: auto;">
              <div class="col ">
                <table class="table table-hover bg-warning ">
                  <thead>
                    <tr>
                      <th>Prdoduto</th>
                      <th>Estoque</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php
                      for ($i=0; !($i == count($this->view->resultMonitEst['itens'])) ; $i++) { 
                        
                    ?>
                        <tr>
                          <td>
                            <a href="/estoque/iten?cd=<?=$this->view->resultMonitEst['itens'][$i]['idFornecimento']?>">
                              <strong><?=$this->view->resultMonitEst['itens'][$i]['produtoNome']?></strong>
                            </a>
                          </td>
                          <td><strong><?=$this->view->resultMonitEst['itens'][$i]['qtdFornecida'] - $this->view->resultMonitEst['itens'][$i]['qtdVendida']?></strong></td>
                        </tr>
                      
                     <?php
                          
                        }
                     ?>
                   </tbody>
                 </table>
              </div>  
            </div>
          <?php
            }
          ?>
        </div>
    </div>
    <div class="row">
      <div class="col pt-2">
        <h4 align="center">Financeiro</h4>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <hr/>
      </div>
    </div>
    <div class="row">
      <div class="col pt-2">
        <h4 align="center">Vendas</h4>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
      </div>
    </div>
  </div>
</div>