<div class="container-fluid" id="corpoAdmim">
	<div class="row">
		<div class="col-md-1" id="menuLatral">
			<nav class ="navbar">
				<ul class ="nav navbar-nav">
					<li class ="nav-item">
						<button type="button" class="btn"  data-toggle="tooltip" data-placement="right" title="Inicio" id="btnInicio">
							<i class="fas fa-home fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn"  data-toggle="tooltip" data-placement="right" title="Desempenho" id="desemprenho">
							<i class="fas fa-chart-bar fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn"  data-toggle="tooltip" data-placement="right" title="Entregas">
							<i class="fas fa-shipping-fast fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn"  data-toggle="tooltip" data-placement="right" title="Pedidos">
							<i class="fas fa-box-open fa-3x" ></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn"  data-toggle="tooltip" data-placement="right" title="Configurações">
							<i class="fas fa-cogs fa-3x"></i>
						</button>
					</li>
				</ul>
			</nav>
		</div>
		<div class="col-md-11" id="areaPainel">
			<div class="row">
				<div class="col-md-10">
					<div class="row"  id="dinamic">

					</div>
				</div>
				<div class="col-md-2">
					<div class="row">
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
						<br>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
