<div class="container-fluid">
	<div class="row">
		<div class="col-md-1" style="background-color: red">
			<div class="row">
				<div class="col-md-6">
					Corpo do painel
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Corpo do painel
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Corpo do painel
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Corpo do painel
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Corpo do painel
				</div>
			</div>
		</div>

		<div class="col-md-11" style="background-color: green">
			<div class="row">
				<div class="col-md-3">
					Corpo do painel
				</div>
				<div class="col-md-3">
					Corpo do painel
				</div>
				<div class="col-md-3">
					Corpo do painel
				</div>
				<div class="col-md-3">
					Corpo do painel
				</div>
		
			</div>
		</div>
	</div>
</div>
