<div class="container-fluid" id="corpoAdmim">
	<div class="row">
		<div class="col-md-1" id="menuLatral">
			<nav class ="navbar">
				<ul class ="nav navbar-nav">
					<li class ="nav-item">
						<button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Inicio" id="btnInicio">
							<i class="fas fa-home fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Desempenho" id="btnDesemprenho">
							<i class="fas fa-chart-bar fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Ativo Passivo" id="btnContas">
							<i class="fas fa-coins fa-3x"></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Estoque" id="btnPedidos">
							<i class="fas fa-cubes fa-4x" ></i>
						</button>
					</li>
					<li class ="nav-item">
						<button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Configurações" id="btnConfig">
							<i class="fas fa-cogs fa-3x"></i>
						</button>
					</li>
				</ul>
			</nav>
		</div>
		<div class="col-md-11" id="areaPainel">
			<div class="row">
				<div class="col-md-10">
					<div class="row"  id="dinamic">

					</div>
				</div>
				<div class="col-md-2" id="optionPlus" style="display: none;">
					
				</div>
			</div>

		</div>
	</div>
</div>
