<div class="container-fuid">
	<div class="row">
		<div class="col-ms-12 col-md-12">
			<h1 align="center">Painel financeiro</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="col">
				<div class="card alert alert-secondary grafic">
			        <div class="card-body">
			        	<div class="row">
			            <div class="col" align="center">
			            	<div class="titleChar h3 text-dark"><strong>Meta</strong></div>
			            </div>
			          </div>
			          <div class="row">
			            <div class="col" align="center">
			              <div style="width: 80%; height: 80%;">
			               <canvas id="metaVenda"></canvas>
			              </div>
			            </div>
			          </div>
			        </div>
			      </div>
			</div>
		</div>
		<div class="col-sm-6 col-md-8">
			<div class="row my-5">
				<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Contas a Pagar</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-danger ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div> 
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Contas a Receber</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-success ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Saldo Real</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-primary ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
			</div>
			<div class="row my-5">
				<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Estoque</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-danger ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div> 
		      	<div class="col">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Estoque</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-danger ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Estoque</strong></h4>
			          </div>
			          <div class="card-body alert pt-5 alert-danger ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>Itens com estoque baixo: </strong></h5>
			              </div>
			            </div>
			            <div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-secondary">Visualizar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
			</div>
		</div>			
	</div>
</div>