<div class="container-fuid" style="height: 48rem">
	<div class="row">
		<div class="col-ms-12 col-md-12">
			<h1 align="center">Painel financeiro</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-md-4">
			<div class="col">
				<div class="card grafic">
			        <div class="card-body">
			        	<div class="row">
			            <div class="col" align="center">
			            	<div class="titleChar h3 text-dark"><strong>Desempenho</strong></div>
			            </div>
			          </div>
			          <div class="row">
			            <div class="col" align="center">
			              <div style="width: 80%; height: 80%;">
			               <canvas id="metaVenda"></canvas>
			              </div>
			            </div>
			          </div>
			        </div>
			      </div>
			</div>
		</div>
		<div class="col-sm-6 col-md-8">
			<div class="row my-5">
				<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Contas a Pagar</strong></h4>
			          </div>
			          <div class="card-body pt-5" style="">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong><a href="#">R$ 500,00</a></strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">XML</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Serviço</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Avulso</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div> 
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Contas a Receber</strong></h4>
			          </div>
			          <div class="card-body pt-5">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>R$ 800,00</strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Visualisar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Caixa</strong></h4>
			          </div>
			          <div class="card-body  pt-5 ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>600,00: </strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Abrir</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Transferir</a>
			              </div>
			               <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Histórico</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
			</div>
			<div class="row my-5">
				<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Funcionarios</strong></h4>
			          </div>
			          <div class="card-body pt-5" style="">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong><a href="#">30</a></strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">visualisar</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Folha</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Vale</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div> 
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Fornecedores</strong></h4>
			          </div>
			          <div class="card-body pt-5">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>8</strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Visualisar</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
		      	<div class="col ">
			        <div class="card" style="border:none;">
			          <div class="card-header" style="border-radius: 30px 30px 0px 0px;">
			            <h4 align="center"><strong>Ordem Serviço</strong></h4>
			          </div>
			          <div class="card-body  pt-5 ">
			            <div class="row">
			              <div class="col" align="center">
			                <h5 class="text-dark"><strong>600,00: </strong></h5>
			              </div>
			            </div>
			          </div>
			          <div class="card-footer">
			          	<div class="row mt-2">
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Criar</a>
			              </div>
			              <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Visualisar</a>
			              </div>
			               <div class="col" align="center">
			                <a href="#" class="btn btn-sm btn-secondary" style="border-radius: 30px;">Recentes</a>
			              </div>
			            </div>
			          </div>
			        </div>
		      	</div>  
			</div>
		</div>			
	</div>
</div>