<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<form method="post" class="was-validated" action="/categoria/salvar" enctype="multipart/form-data" style="" id="cadastrarCategoria">
			<fieldset class=""><legend><strong>Cadastrar Categoria</strong></legend>
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="form-group">
							<label for="idCategoria">Categoria:</label>
							<input type="text" name="categoria" id="idCategoria" class="form-control" placeholder="Nome da categoria" required="required">
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Cadastrar</button> <a href="/produto/cadastrar" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>
	</div>
</div>