<div class="row" style="background-color: #fff; width: 60%;" align="left">
	<div class="col-md-12 py-4 px-4" style="margin: auto;">
		<div class="row">
			<div class="col" align="center"><h2><strong>Seus pagamentos</strong></h2></div>
		</div>
		<div class="row">
			<div class="col-sm-12 py-3">
				<strong>Seus cartões:</strong><br>
				<table class="table table-hover table-responsive mt-2" id="cartoes">
					<thead>
				      <tr>
				        <th>Nome</th>
				        <th>Tipo</th>
				        <th>Final</th>
				        <th>Ação</th>
				      </tr>
				    </thead>
				    <tbody>
				    	<tr>
					    	<td>Visa</td>
					        <td>Credito</td>
					        <td>0045</td>
					        <td>
					        	<a href="#" class="btn btn-sm btn-primary"  style="background-color: #9400D3">Editar</a>
					        	<a href="#" class="btn btn-sm btn-danger">Excluir</a>
					        </td>
					    </tr>
				    </tbody>
				</table>
				
			</div>		
		</div>
		<div class="row">
			<div class="col">
				<strong>Adicione uma forma de pagamento:</strong>
			</div>
		</div>
		<div class="row">
			<div class="col py-3">
				<strong>Cartão de débito:</strong><br>
				<a href="#" class="btn btn-sm btn-primary">adicicionar</a>
			</div>
		</div>
		<div class="row">
			<div class="col py-3">
				<strong>Cartão de crédito:</strong><br>
				<a href="#" class="btn btn-sm btn-primary">adicicionar</a>
			</div>
		</div>
	</div>
</div>