<div class="row" id="vitrine-home">
	<div class="col-md-12" >
		<div class="row" style="width: 80%; margin: auto;">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div id="demo" class="carousel slide" data-ride="carousel">
							<ul class="carousel-indicators">
							    <li data-target="#demo" data-slide-to="0" class="active"></li>
							    <li data-target="#demo" data-slide-to="1"></li>
							    <li data-target="#demo" data-slide-to="2"></li>
							</ul>
							<div class="carousel-inner">
							    <div class="carousel-item active">
							      	<img src="files/imagens/images.png" style="width: 100%;height: 500px;"/>
							    </div>
							    <div class="carousel-item">
							      	<img src="files/imagens/smartphonesamssung.jpeg" style="width: 100%;height: 500px;"/>
							    </div>
							    <div class="carousel-item">
							      	<img src="files/imagens/teclado.jpeg" style="width: 100%;height: 500px;"/>
							    </div>
							</div>
							<a class="carousel-control-prev" href="#demo" data-slide="prev">
							    <span class="carousel-control-prev-icon"></span>
							</a>
							<a class="carousel-control-next" href="#demo" data-slide="next">
							    <span class="carousel-control-next-icon"></span>
							</a>
						</div>
					</div>
				</div>


				<?php 
				
					

						$bloco = $this->view->categorias;

						for ($j=0; !($j == count($bloco)); $j++) { 
						//
							
								
			           
				 ?>
				 <div class="row mt-4"><!-- Bloco de grid-->
					 <?php 	
					 		$linha = $bloco[$j];

					 		$classCol = (12/count($linha));//define a classe da coluna no gride de fotos

					 		
							for ($h=0; !($h == count($linha) ); $h++) { 
								$categ = ucfirst(strtolower($linha[$h]));

					 			$products = $this->view->arrProdIndexCat[$linha[$h]];//armazena os produtos da categoria
					 			
								$totProducts = count($products); 
								
				 				$toorLoja = null;
						  		if(count($linha) == 4 ){//total de fotos
						  			if(($h==0) && ($i ==0) && ($j ==0)){
						  				$toorLoja = 'Toor pela loja';
						  			}
							  			
							  	?>
							  	<div class="col-md-3">
									<div class="card" style="width: 22rem;">
									  <div class="card-body">
									  	<div class="row">
									  		<div class="col-md-12">
									  			<h4><strong><?= isset($toorLoja) ? $toorLoja: $categ?></strong></h4>
									  		</div>
									  	</div>
									    <div class="row">
									    	<?php

									    		$sentinela =0;
									 		
									    		while (!($sentinela == 4)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $products))	{
									    				$urlIdEst = explode('-', $products[$sentinela]);
									    				$img = $urlIdEst[0];
									    				$id = $urlIdEst[1];
									    				$estoque = (int)$urlIdEst[2];

									    				$msg = ($estoque == 0)? '<p class="text-danger" style="position: absolute; top: 110px;left:10px;">
									    				<strong>sem estoque</strong></p>':'' 
									    				
									    	?>
										    	<div class="col-md-<?=$cols?> py-2 px-2  my-2" style="position: relative;">
										    		<a href="/pedido/produto/detalhes?cd=<?=$id?>" class="link-produto " ><img style="width: 100px; height: 100px;" class="card-img-top a-img-product"  src="files/imagens/<?=$img;?>" alt=""></a>
										    			<?= $msg ?>
										    	</div>
									    	<?php 
									    		}	
									    		$sentinela++;
									    	}
									    	?>
									    </div>
									  </div>
									  <div class="card-footer">
									  	<p><a href="#">Ver mais</a></p>
									  </div>
									</div>
								</div>
								  
							    <?php
							    	}else if(count($linha) == 2){


							     ?>
							 	<div class="col-md-6">
									<div class="card" style="width: 46rem;">
										<div class="card-body">
											<div class="row">
												<div class="col-md-12">
													<h4><strong><?=$categ?></strong></h4><a href="#">Ver mais</a>
												</div>
											</div>
											<div class="row">
												<?php									    		

									    		$sentinela =0;
									    		
									    		while (!($sentinela == 4)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $products))	{

										    			$urlIdEst = explode('-', $products[$sentinela]);
									    				$img = $urlIdEst[0];
									    				$id = $urlIdEst[1];
									    				$estoque = (int)$urlIdEst[2];

									    				$msg = ($estoque == 0)? '<p class="text-danger" style="position: absolute; top: 110px;left:10px;">
									    				<strong>sem estoque</strong></p>':'' 
									    	?>
										    	<div class="col py-2 px-2">
										    		<a href="/pedido/produto/detalhes?cd=<?=$id?>" class="link-produto my-2" ><img style="width: 100px; height: 100px;" class="card-img-top a-img-product" src="files/imagens/<?=$img?>" alt="imagem"></a>
										    		<?= $msg ?>
										    	</div>
									    	<?php 
									    		}

									    		$sentinela++;
									    		}
									    	?>
												
											</div>
										</div>
									</div>
								</div>

							     <?php
							     	}else if(count($linha) == 1){
							      ?>
							      <div class="col-md-12">
									<div class="card" style="width: 93.5rem;">
									  <div class="card-body">
									  	<div class="row">
									  		<div class="col-md-12">
									  			<h4><strong><?=$categ?></strong></h4></h4>
									  		</div>
									  	</div>
									    <div class="row">
									    	<?php
									    		
									    		$sentinela =0;
									 
									    		while (!($sentinela == 6)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $products))	{

										    			$urlIdEst = explode('-', $products[$sentinela]);
									    				$img = $urlIdEst[0];
									    				$id = $urlIdEst[1];
									    				$estoque = (int)$urlIdEst[2];

									    				$msg = ($estoque == 0)? '<p class="text-danger" style="position: absolute; top: 110px;left:10px;">
									    				<strong>sem estoque</strong></p>':'' 
									    	?>
										    	<div class="col" style="position: relative;">
										    		<a href="/pedido/produto/detalhes?cd=<?=$id?>" class="link-produto my-2" ><img style="width: 105px; height: 100px;" class="card-img-top py-2 px-2 a-img-product hidBtn" src="files/imagens/<?=$img?>" alt="<?=$img?>"></a><br>
										    		<a href="#" class="btn btn-primary" style="position: absolute; top: 100px; left: auto; margin:auto;display: none;">Ver mais</a>
										    		<?= $msg ?>
										    	</div>
									    	<?php 
									    			}
									    		$sentinela++;
									    		}
									    	?>
												
									    	
									    </div>
									  </div>
									</div>
								</div>
								    
							      <?php 
							      	}
							      ?>
					
						
					
					<?php 

							}
					?>
					</div> <!-- Finaliza o grid-->
					<?php 
						}
					
					?>
				
				
			</div><br>
		</div>
	</div>
</div>


