<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div id="demo" class="carousel slide" data-ride="carousel">
				<ul class="carousel-indicators">
				    <li data-target="#demo" data-slide-to="0" class="active"></li>
				    <li data-target="#demo" data-slide-to="1"></li>
				    <li data-target="#demo" data-slide-to="2"></li>
				</ul>
				<div class="carousel-inner">
				    <div class="carousel-item active">
				      	<img src="files/imagens/images.png" style="width: 100%;height: 500px;"/>
				    </div>
				    <div class="carousel-item">
				      	<img src="files/imagens/xbox_controller.jpeg" style="width: 100%;height: 500px;"/>
				    </div>
				    <div class="carousel-item">
				      	<img src="files/imagens/xbox_controller.jpeg" style="width: 100%;height: 500px;"/>
				    </div>
				</div>
				<a class="carousel-control-prev" href="#demo" data-slide="prev">
				    <span class="carousel-control-prev-icon"></span>
				</a>
				<a class="carousel-control-next" href="#demo" data-slide="next">
				    <span class="carousel-control-next-icon"></span>
				</a>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Toor pela loja</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Ofertas do dia</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Interessantes</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-6">
			<div class="card" style="width: 34rem;">
				<div class="card-body">
					<div class="row">
						<div class="col-md-12">
							<h3>Dispositivos Móveis</h3><a href="#">Ver mais</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card" style="width: 34rem;">
				<div class="card-body">
					<div class="row">
						<div class="col-md-12">
							<h3>Computadores e Informática</h3><a href="#">Ver mais</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Moda</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Esportivo</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Do dia a dia</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-12">
			<div class="card" style="width: 69.5rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Câmeras e Fotos</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Para brincar com o seu pet</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Relógios</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>40% off em eBooks</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-6">
			<div class="card" style="width: 34rem;">
				<div class="card-body">
					<div class="row">
						<div class="col-md-12">
							<h3>Dispositivos Móveis</h3><a href="#">Ver mais</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card" style="width: 34rem;">
				<div class="card-body">
					<div class="row">
						<div class="col-md-12">
							<h3>Computadores e Informática</h3><a href="#">Ver mais</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
						<div class="col-md-3">
							<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Moda</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Esportivo</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-12">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap" style="height: 100%; width: 91%;"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card" style="width: 22rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Do dia a dia</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    </div>
			     <div class="row">
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/images.png" alt="Card image cap"></a>
			    	</div>
			    	<div class="col-md-6">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			  <div class="card-footer">
			  	<p><a href="#">Ver mais</a></p>
			  </div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col-md-12">
			<div class="card" style="width: 69.5rem;">
			  <div class="card-body">
			  	<div class="row">
			  		<div class="col-md-12">
			  			<h4><strong>Mais Vendidos em Livros</strong></h4>
			  		</div>
			  	</div>
			    <div class="row">
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    	<div class="col">
			    		<a href="#"><img class="card-img-top" src="files/imagens/xbox_controller.jpeg" alt="Card image cap"></a>
			    	</div>
			    </div>
			  </div>
			</div>
		</div>
	</div>
</div><br>
