<div class="row" id="vitrine-home">
	<div class="col-md-12" >
		<div class="row" style="width: 80%; margin: auto;">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div id="demo" class="carousel slide" data-ride="carousel">
							<ul class="carousel-indicators">
							    <li data-target="#demo" data-slide-to="0" class="active"></li>
							    <li data-target="#demo" data-slide-to="1"></li>
							    <li data-target="#demo" data-slide-to="2"></li>
							</ul>
							<div class="carousel-inner">
							    <div class="carousel-item active">
							      	<img src="files/imagens/images.png" style="width: 100%;height: 500px;"/>
							    </div>
							    <div class="carousel-item">
							      	<img src="files/imagens/smartphonesamssung.jpeg" style="width: 100%;height: 500px;"/>
							    </div>
							    <div class="carousel-item">
							      	<img src="files/imagens/teclado.jpeg" style="width: 100%;height: 500px;"/>
							    </div>
							</div>
							<a class="carousel-control-prev" href="#demo" data-slide="prev">
							    <span class="carousel-control-prev-icon"></span>
							</a>
							<a class="carousel-control-next" href="#demo" data-slide="next">
							    <span class="carousel-control-next-icon"></span>
							</a>
						</div>
					</div>
				</div>


				<?php
					for ($i=0, $categorias = $this->view->categorias; !($i == count($categorias)) ; $i++) { 

						$bloco = $categorias[$i];
						for ($j=0; !($j == count($bloco)); $j++) { 
						//
							
								
			           
				 ?>
				 <div class="row mt-4"><!-- Bloco de grid-->
					 <?php 	
					 		$linha = $bloco[$j];

					 		$classCol = (12/count($linha));//define a classe da coluna no gride de fotos

					 		
							for ($h=0; !($h == count($linha) ); $h++) { 
								$categ = ucfirst(strtolower($linha[$h]));

					 			$products = $this->view->arrProdIndexCat[$linha[$h]];//armazena os produtos da categoria
					 			
								$totProducts = count($products); 
								//conta quantos tem dessa categoria


								$urlImg = [];

								foreach ($products as $key=> $value){ //verifica de o produto tras essa categoria comssigo
									for ($k=0; !($k== count($value)) ; $k++) { 

										$result = $value[$k]->getNomeCategoria() == $linha[$h];
										if($result){
											$urlImg[] = $key;
										}
									}
								}

					 				$toorLoja = null;
							  		if(count($linha) == 4 && ($urlImg != null)){//total de fotos
							  			if(($h==0) && ($i ==0) && ($j ==0)){
							  				$toorLoja = 'Toor pela loja';
							  			}
							  			
							  	?>
							  	<div class="col-md-3">
									<div class="card" style="width: 20rem;">
									  <div class="card-body">
									  	<div class="row">
									  		<div class="col-md-12">
									  			<h4><strong><?= isset($toorLoja) ? $toorLoja: $categ?></strong></h4>
									  		</div>
									  	</div>
									    <div class="row">
									    	<?php

									    		$sentinela =0;
									 		
									    		while (!($sentinela == 4)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $urlImg)){
									    				$urlImgId = explode('-', $urlImg[$sentinela]);
									    				$img = $urlImgId[0];
									    				$id = $urlImgId[1];
									    				
									    	?>
										    	<div class="col-md-<?=$cols?> py-2 px-2 a-img-product">
										    		<a href="/produto/detals?cd=<?=$id?>"><img style="width: 100px; height: 100px;" class="card-img-top" src="files/imagens/<?=$img;?>" alt=""></a>
										    	</div>
									    	<?php 
									    			}
									    		$sentinela++;
									    		}
									    	?>
									    </div>
									  </div>
									  <div class="card-footer">
									  	<p><a href="#">Ver mais</a></p>
									  </div>
									</div>
								</div>
								  
							    <?php
							    	}else if((count($linha) == 2)  && ($urlImg != null)){


							     ?>
							 	<div class="col-md-6">
									<div class="card" style="width: 42rem;">
										<div class="card-body">
											<div class="row">
												<div class="col-md-12">
													<h4><strong><?=$categ?></strong></h4><a href="#">Ver mais</a>
												</div>
											</div>
											<div class="row">
												<?php									    		

									    		$sentinela =0;
									 
									    		while (!($sentinela == 4)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $urlImg)){
									    				$urlImgId = explode('-', $urlImg[$sentinela]);
									    				$img = $urlImgId[0];
									    				$id = $urlImgId[1];
									    	?>
										    	<div class="col py-2 px-2 a-img-product">
										    		<a href="/produto/detals?cd=<?=$id?> "><img style="width: 100px; height: 100px;" class="card-img-top" src="files/imagens/<?=$img?>" alt="imagem"></a>
										    	</div>
									    	<?php 
									    			}
									    		$sentinela++;
									    		}
									    	?>
												
											</div>
										</div>
									</div>
								</div>

							     <?php
							     	}else if($urlImg !=null){
							      ?>
							      <div class="col-md-12">
									<div class="card" style="width: 86rem;">
									  <div class="card-body">
									  	<div class="row">
									  		<div class="col-md-12">
									  			<h4><strong><?=$categ?></strong></h4></h4>
									  		</div>
									  	</div>
									    <div class="row">
									    	<?php
									    		
									    		$sentinela =0;
									 
									    		while (!($sentinela == 6)) {

									    			//configura largura da coluna
									    			$cols = 6;
										    		switch ($totProducts) {
										    			case 1:
										    				$cols = 12;
										    				break;
									    			}

									    			if(array_key_exists($sentinela, $urlImg)){
									    				$urlImgId = explode('-', $urlImg[$sentinela]);
									    				$img = $urlImgId[0];
									    				$id = $urlImgId[1];
									    	?>
										    	<div class="col" style="position: relative;">
										    		<a href="/produto/detals?cd=<?=$id?>"><img style="width: 105px; height: 100px;" class="card-img-top py-2 px-2 a-img-product hidBtn" src="files/imagens/<?=$img?>" alt=""></a><br>
										    		<a href="#" class="btn btn-primary" style="position: absolute; top: 100px; left: auto; margin:auto;display: none;">Ver mais</a>
										    	</div>
									    	<?php 
									    			}
									    		$sentinela++;
									    		}
									    	?>
												
									    	
									    </div>
									  </div>
									</div>
								</div>
								    
							      <?php 
							      	}
							      ?>
					
						
					
					<?php 

							}
					?>
					</div> <!-- Finaliza o grid-->
					<?php 
						}
					
					?>
				<?php
					}
				?>	
				
				
			</div><br>
		</div>
	</div>
</div>


