<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap.min.css">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="../styles/more_styles/menu_header_site/loja_styles.css">
    <link rel="stylesheet" href="../fontawesome/css/all.css">
    <link rel="stylesheet" href="../jquery/jquery-ui/jquery-ui.min.css">
    
    <script src="../jquery/jquery.min_google.js"></script>
    <script src="../jquery/jquery-ui/jquery-ui.min.js"></script>
    <script src="../jquery/plugins/elevatezoom-master/jquery.elevatezoom.js" type="text/javascript"></script>
    <script src="../styles/bootstrap-4/js/bootstrap.min.js"></script>
    <script src="../fontawesome/js/all.js"></script>
    <!--<script type="text/javascript" src=
"https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>-->
<script type="text/javascript" src=
"https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
    
    <script src="../js/jsLoja.js"></script>

    <script src="../ajax/pagseguro.js"></script>
    <script type="text/javascript" src="../js/bibliotecas/chart.js"></script>
    <title>Minha-Loja.com</title>
</head>
  <body id="bodyLojaVirtual" style="background-color: #fff;">
      <section class="container" id="section-login">
        <div class="row">
            <div class="col bem-vindo" style="width: 50%;">
              <span style="font-size: 48px; color: #8B008B;">
               <i class="far fa-user fa-2x"></i>
              </span>
            </div>
        </div>
        <div class="row mb-3">
          <div class="col">
            <div class="bem-vindo">Bem-Vindo(a) ao MinhaLoja.com</div>
          </div>
        </div>
      	<div class="row">
      		<div class="col-ms-12 col-md-12" style="margin: auto;" id="login-user">
		         <form method="post" action="/home/login/logar" class="was-validated" novalidate style="width: 50%;margin: auto; padding: 20px 30px;">
				    <hr/>
				    <div class="form-group">
				        <label for="id_email">Email</label>
				        <input type="email" name="usuario" id="id_email" class="form-control" placeholder="exemplo@gmail.com" required>
				        <!--
				        <div class="valid-feedback">Valido.</div>
				        <div class="invalid-feedback">Por favor, preencha este campo.</div>
				        -->
				    </div>
				    <div class="form-group">
				        <label for="id_password">Senha</label>
				        <input type="password" name="senha" id="id_password" class="form-control" required>
				        <!--
				        <div class="valid-feedback">Valido.</div>
				        <div class="invalid-feedback">Por favor, preencha este campo.</div>
				        -->
				    </div>
				    <div class="form-group form-check">
				      <label class="form-check-label">
				        <input class="form-check-input" type="checkbox" name="manter"> Manter-me conectado.
				      </label>
				    </div>
				    <div class="form-group rodape" style="display: flex; justify-content: space-between;">
				        <button type="submit" class="btn btn-success">Entrar</button>
				        <a href="/pessoa/cadastrar" class="link" id="novo-cadastro">Inda não sou cadastrado(a)</a>
				    </div>
				</form>
			</div>
		</div>
      </section>
      <footer>
      <!-- The Modal -->
      <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-sm modal-lg modal-xl modal-dialog-centered">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Modal Heading</h4>
              <button type="button" class="close" data-dismiss="modal" id="closeModal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              
            </div>

          </div>
        </div>
      </div>

      </footer>

      <script type="text/javascript">
        $(document).ready(function(){

          $('body').delegate('a#novo-cadastro', 'click', function(ev){
            ev.preventDefault();
            let url  = $(this).attr('href');
            $.ajax({
              url: url,
              type: 'GET',
              dataType: 'HTML',
              success: function(retorno){
                $('#login-user').html(retorno);
              }
            })
          })

          $('body').delegate('form#cadastro-pessoa', 'submit', function(ev){
            ev.preventDefault();
            let form = $(this);

            let error = new Array();

            form.find('input').each(function(){
              let inputNow = $(this);
              let name = inputNow.attr('name');

              let val = inputNow.val();

              if(val.trim().length == 0){
                switch(name.trim()){
                  case 'documento':
                    error.push('Preencha o campo de "CPF", por favor.');
                  break;

                  case 'nome_complementar':
                    error.push('Preencha o campo de "Sobrenome", por favor.');
                  break;

                  case 'documento_complementar':
                    error.push('Preencha o campo de "RG", por favor.');
                  break;

                  case 'sexo':
                    error.push('Preencha o campo de "SEXO", por favor.');
                  break;

                  case 'login':
                    error.push('Preencha o campo de "LOGIN", por favor.');
                  break;

                  case 'senha':
                    error.push('Preencha o campo de "SENHA", por favor.');
                  break;

                  case 'nome':
                    error.push('Preencha o campo de "NOME", por favor.');
                  break;
                }
                
              }else{

                 switch(name.trim()){
                  case 'documento':
                      if(validaCpf(val.trim()) == false){

                       error.push('O CPF informado é inválido');
                      }else if(val.trim().length != 11){
                        error.push('O CPF deve ter 11 caracteres');
                      }

                  break;
                  case 'nome_complementar':
                    if(val.trim().length < 3){

                        error.push('O sobrnome deve ter entre 3 e 200 caracteres');
                      }else if(val.trim().length > 200){
                        error.push('O sobrnome deve ter entre 3 e 200 caracteres');
                      }
                  break;

                  case 'documento_complementar':
                    if(val.trim().length != 13){
                        error.push('O Rg deve ter 13 caracteres');
                      }

                  break;

                  case 'sexo':
                    if((val.trim() != 'F') && (val.trim() != 'M')){

                        error.push('O sexo informado é inválido!');
                      }
                  break;

                  case 'login':
                    if(val.trim().length < 12){

                        error.push('Email inválido');
                      }else if(val.trim().length > 100){
                        error.push('Email deve ter entre 12 e 100 caracteres');
                      }
                  break;

                  case 'senha':
                    if((val.trim().length < 9) || (val.trim().length > 200)){

                        error.push('Informe uma senha que tenha entre 9 e 12 caracteres!');
                      }
                  break;

                  case 'nome':
                    if(val.trim().length < 3){

                        error.push('O nome deve ter entre 3 e 200 caracteres!');
                      }else if(val.trim().length > 200){
                         error.push('O nome deve ter entre 3 e 200 caracteres!');
                      }
                  break;
                }

              }

            })

            let url  = $(this).attr('action');

            let objForm = new  FormData(form[0]);
            if(error.length == 0){

                $.ajax({
                  url: url,
                  type: 'POST',
                  data: objForm,
                  dataType: 'json',
                  processData: false,
                  contentType: false,
                  success: function(retorno){ 

                    $('#retorno').remove();

                    if(retorno[1] == 'success'){
                      $('#section-login').html('');
                    }

                    let msg = $('<div/>').addClass('row').attr('id', 'retorno');
                    msg.append($('<div/>').addClass('col alert alert-'+retorno[1]).html(retorno[2]))
                    
                    $('#section-login').prepend(msg);
                  }
                })
              }else{
                let msg = 'Atenção: \n\n';
                for (let i = 0; !(i == error.length); i++) {
                  msg+= error[i]+'\n';
                }
                alert(msg);
                return false;
              }

          })



          function validaCpf(cpf){
            cpf = cpf.replace(/[^\d]+/g, '');

            if(cpf.length != 11){
              return false;
            }
            
            let splitCpf = cpf.split('');

            let digitoUm = 0;
            let digitoDois = 0;

            

            for (let i=0, x=1; !(i == 9 ); i++, x ++) { 
                 digitoUm += splitCpf[i] * x;
            }

            

            for (let i=0,  y=0; !(i == 10 ); i++, y ++) { 

                let invaliCpf = '';

                for (let j = 0; !(j == 11); j++) {
                  invaliCpf += i;
                }

                if(invaliCpf == cpf){
                    return false;
                }


                digitoDois += splitCpf[i] * y;
            }

            let calculoUm = ((digitoUm % 11) == 10) ? 0 : (digitoUm % 11);
            let calculoDois = ((digitoDois % 11) == 10) ? 0 : (digitoDois % 11);

            if((calculoUm != splitCpf[9]) || (calculoDois != splitCpf[10])){
                return false;
            }

            return true;

          }

        })
      </script>
  </body>
</html>