<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap.min.css">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="../styles/more_styles/menu_header_site/loja_styles.css">
    <link rel="stylesheet" href="../fontawesome/css/all.css">
    <link rel="stylesheet" href="../jquery/jquery-ui/jquery-ui.min.css">
    
    <script src="../jquery/jquery.min_google.js"></script>
    <script src="../jquery/jquery-ui/jquery-ui.min.js"></script>
    <script src="../jquery/plugins/elevatezoom-master/jquery.elevatezoom.js" type="text/javascript"></script>
    <script src="../styles/bootstrap-4/js/bootstrap.min.js"></script>
    <script src="../fontawesome/js/all.js"></script>
    <!--<script type="text/javascript" src=
"https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>-->
<script type="text/javascript" src=
"https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
    
    <script src="../js/jsLoja.js"></script>

    <script src="../ajax/pagseguro.js"></script>
    <script type="text/javascript" src="../js/bibliotecas/chart.js"></script>
    <title>Minha-Loja.com</title>
</head>
  <body id="bodyLojaVirtual" style="background-color: #fff;">
      <section class="container" id="">
      	<div class="row">
      		<div class="col-ms-12 col-md-12" style="margin: auto;">
		         <form method="post" action="/home/login/logar" class="was-validated" novalidate style="width: 50%;margin: auto; padding: 20px 30px;">
				    <div class="form-group bem-vindo">
				      <span style="font-size: 48px; color: #8B008B;">
				       <i class="far fa-user fa-2x"></i>
				      </span>
				    </div>
				    <div class="form-group bem-vindo">Bem-Vindo(a) ao MinhaLoja.com</div>
				    <hr/>
				    <div class="form-group">
				        <label for="id_email">Email</label>
				        <input type="email" name="usuario" id="id_email" class="form-control" placeholder="exemplo@gmail.com" required>
				        <!--
				        <div class="valid-feedback">Valido.</div>
				        <div class="invalid-feedback">Por favor, preencha este campo.</div>
				        -->
				    </div>
				    <div class="form-group">
				        <label for="id_password">Senha</label>
				        <input type="password" name="senha" id="id_password" class="form-control" required>
				        <!--
				        <div class="valid-feedback">Valido.</div>
				        <div class="invalid-feedback">Por favor, preencha este campo.</div>
				        -->
				    </div>
				    <div class="form-group form-check">
				      <label class="form-check-label">
				        <input class="form-check-input" type="checkbox" name="manter"> Manter-me conectado.
				      </label>
				    </div>
				    <div class="form-group rodape" style="display: flex; justify-content: space-between;">
				        <button type="submit" class="btn btn-success">Entrar</button>
				        <a href="/home/cadastro" class="link">Inda não sou cadastrado(a)</a>
				    </div>
				</form>
			</div>
		</div>
      </section>
      <footer>
      <!-- The Modal -->
      <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-sm modal-lg modal-xl modal-dialog-centered">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Modal Heading</h4>
              <button type="button" class="close" data-dismiss="modal" id="closeModal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              
            </div>

          </div>
        </div>
      </div>

      </footer>
  </body>
</html>