<div class="container-fluid" id="">
	<div class="row" id="menuAmin">
		<div class="col-md-12" id="subPainel">
			<div class="row" id="menuSupAdmin">
				<div class="col-md-8 col-sm-9 col-xs-9">
					<div class="row">
						<div class="col" id="divImgAdmin">
							<img src="../files/imagens/perfil/pedroPerfil.jpeg" class="rounded-circle" align="center"><span align="left">Hello, <strong>Phedro</strong>, Welcome Back!</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-3 col-xs-3">
					<div class="row" align="right">
						<div class="col" align="right">
							<span class="btn"><i class="fas fa-envelope fa-2x"></i></span>
						</div>
						<div class="col" align="right">
							<span class="btn"><i class="far fa-bell  fa-2x"></i></span>
						</div>
						<div class="col" align="right">
							<form class="search">
								<input type="text" class="searchInput" name="" style="">
								<button><i class="fas fa-search"></i></button>
							</form>
						</div>
						<div class="col" >
							<span class="btn" style="color: #9400D3;" id="menuAdminHide" data-toggle="modal" data-target="#myModal"><i class="fas fa-bars fa-2x"></i></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>