<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap.min.css">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="../styles/more_styles/menu_header_site/adminStyles.css">
    <link rel="stylesheet" href="../fontawesome/css/all.css">
    <link rel="stylesheet" href="../jquery/jquery-ui/jquery-ui.min.css">
    <link rel="manifest" href="../manifest.json">
        <!-- CODELAB: Add iOS meta tags and icons -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Weather PWA">
    <link rel="apple-touch-icon" href="/images/icons/icon-152x152.png">
    
    <script src="../jquery/jquery.min_google.js"></script>
    <script src="../jquery/jquery-ui/jquery-ui.min.js"></script>
    <script src="../styles/bootstrap-4/js/bootstrap.min.js"></script>
    <script src="../fontawesome/js/all.js"></script>
    <script type="text/javascript" src='https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js'></script>
    <script src="../js/paginasJs.js"></script>
    <script src="../js/jsApplication.js"></script>

    <script src="../ajax/pagseguro.js"></script>
    <script type="text/javascript" src="../js/bibliotecas/chart.js"></script>
    <title>Minha-Loja.com</title>
</head>
<body>
    <header>
        <?php $this->loadMenu(); ?>
    </header>
    <section class="">
      <div class="container-fluid" id="corpoAdmim">
        <div class="row">
          <div class="col-md-1 col-sm-1 col-xs-1" id="menuLatral">
            <nav class ="nav">
              <ul class ="nav">
                <li class ="nav-item">
                  <button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Inicio" id="btnInicio">
                    <i class="fas fa-home fa-3x"></i>
                  </button>
                </li>
                <li class ="nav-item">
                  <button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Desempenho" id="btnDesemprenho">
                    <i class="fas fa-chart-bar fa-3x"></i>
                  </button>
                </li>
                <li class ="nav-item">
                  <button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Ativo Passivo" id="btnContas">
                    <i class="fas fa-coins fa-3x"></i>
                  </button>
                </li>
                <li class ="nav-item">
                  <button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Estoque" id="btnPedidos">
                    <i class="fas fa-cubes fa-4x" ></i>
                  </button>
                </li>
                <li class ="nav-item">
                  <button type="button" class="btn btnIcones"  data-toggle="tooltip" data-placement="right" title="Configurações" id="btnConfig">
                    <i class="fas fa-cogs fa-3x"></i>
                  </button>
                </li>
                <li class ="nav-item">
                  <a href="/" target="_balck" class="btn btnIcones px-3"  data-toggle="tooltip" data-placement="right" title="Site">
                    <i class="fas fa-window-maximize fa-3x"></i>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <div class="col-md-11 col-sm-11" id="areaPainel">
            <div class="container-fluid">
              <div class="row mt-3 mb-3 ml-1 mr-1">
                <div class="col-md-9 col-sm-12"  id="dinamic">

                  <?php $this->content($view_path); ?>

                </div>

                <div class="col-md-3 col-sm-12" id="optionPlus">
                  <div class="row ml-3 mb-2" style=" background-color: #fff;padding: 5px;" >
                    <div class="col">
                    <div class="row">
                        <div class="col pt-2">
                          <h4 align="center">Estoque</h4>
                          <?php
                            if(isset($this->view->resultMonitEst) && (count($this->view->resultMonitEst) > 0)){


                          ?>
                            <div class="row">
                              <div class="col">
                                <h5 class="text-dark"><strong>T. Estoque baixo:</strong> <?=$this->view->resultMonitEst['qtdItens']?></h5>
                              </div>
                            </div>
                            <div class="row" style="height: 200px; overflow-y: auto;">
                              <div class="col ">
                                <table class="table table-hover bg-warning ">
                                  <thead>
                                    <tr>
                                      <th>Prdoduto</th>
                                      <th>Estoque</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <?php
                                      for ($i=0; !($i == count($this->view->resultMonitEst['itens'])) ; $i++) { 
                                        
                                    ?>
                                        <tr>
                                          <td>
                                            <a href="/estoque/iten?cd=<?=$this->view->resultMonitEst['itens'][$i]['idFornecimento']?>">
                                              <strong><?=$this->view->resultMonitEst['itens'][$i]['produtoNome']?></strong>
                                            </a>
                                          </td>
                                          <td align="right"><strong><?=$this->view->resultMonitEst['itens'][$i]['qtdFornecida'] - $this->view->resultMonitEst['itens'][$i]['qtdVendida']?></strong></td>
                                        </tr>
                                      
                                     <?php
                                          
                                        }
                                     ?>
                                   </tbody>
                                 </table>
                              </div>  
                            </div>
                          <?php
                            }
                          ?>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col pt-2">
                        <h4 align="center">Financeiro</h4>
                       <?php
                            if(isset($this->view->resultMonitEst) && (count($this->view->resultMonitEst) > 0)){


                          ?>
                            <div class="row">
                              <div class="col">
                                <h5 class="text-dark"></h5>
                              </div>
                            </div>
                            <div class="row" style="height: 200px; overflow-y: auto;">
                              <div class="col ">
                                <table class="table table-hover bg-success ">
                                  <thead>
                                    <tr>
                                      <th>Prdoduto</th>
                                      <th>Estoque</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <?php
                                      for ($i=0; !($i == count($this->view->resultMonitEst['itens'])) ; $i++) { 
                                        
                                    ?>
                                        <tr>
                                          <td>
                                            <a href="/estoque/iten?cd=<?=$this->view->resultMonitEst['itens'][$i]['idFornecimento']?>">
                                              <strong>***********</strong>
                                            </a>
                                          </td>
                                          <td><strong>***********</strong></td>
                                        </tr>
                                      
                                     <?php
                                          
                                        }
                                     ?>
                                   </tbody>
                                 </table>
                              </div>  
                            </div>
                          <?php
                            }
                          ?>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col pt-2">
                        <h4 align="center">Vendas</h4>
                        <?php
                            if(isset($this->view->resultMonitEst) && (count($this->view->resultMonitEst) > 0)){


                          ?>
                            <div class="row">
                              <div class="col">
                                <h5 class="text-dark"><strong></strong></h5>
                              </div>
                            </div>
                            <div class="row" style="height: 200px; overflow-y: auto;">
                              <div class="col ">
                                <table class="table table-hover bg-primary ">
                                  <thead>
                                    <tr>
                                      <th>Prdoduto</th>
                                      <th>Estoque</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <?php
                                      for ($i=0; !($i == count($this->view->resultMonitEst['itens'])) ; $i++) { 
                                        
                                    ?>
                                        <tr>
                                          <td>
                                            <a href="/estoque/iten?cd=<?=$this->view->resultMonitEst['itens'][$i]['idFornecimento']?>">
                                              <strong>***********</strong>
                                            </a>
                                          </td>
                                          <td><strong>***********</strong></td>
                                        </tr>
                                      
                                     <?php
                                          
                                        }
                                     ?>
                                   </tbody>
                                 </table>
                              </div>  
                            </div>
                          <?php
                            }
                          ?>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </section>
    <footer>

      <?php $this->loadFooter(); ?>

  
    <div class="modal fade" id="myModal">
      <div class="modal-dialog modal-sm modal-lg modal-xl modal-dialog-centered">
        <div class="modal-content">

          
          <div class="modal-header">
            <h4 class="modal-title">Modal Heading</h4>
            <button type="button" class="close" data-dismiss="modal" id="closeModal">&times;</button>
          </div>

          
          <div class="modal-body">
            Modal body..
          </div>
          <div class="modal-footer">
            
          </div>

        </div>
      </div>
    </div>

    </footer>
  </body>
</html>