<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../styles/bootstrap-3/css/bootstrap.min.css">
    <link rel="stylesheet" href="../styles/more_styles/menu_header_site/loja_styles.css">
    <link rel="stylesheet" href="../fontawesome/css/all.css">

    <script src="../styles/bootstrap-3/js/bootstrap.min.js"></script>
    <script src="../fontawesome/js/all.js"></script>
    <script type="text/javascript" src='https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js'></script>
    <script src="../jquery/jquery.js"></script>
    <script src="../js/valida_login.js"></script>
    <script src="../ajax/pagseguro.js"></script>
    <title>Minha-Loja.com</title>
</head>
<body>
    <header>
        <?php echo $this->loadMenu(); ?>
    </header>
    <section class="">
        <?php echo $this->content($view_path); ?>
    </section>
    <footer>

    </footer>
</body>
</html>