<div class="row">
	<div class="col-md-3">
		<nav class ="nav" align="center">
	     	<ul class="nav nav-pills flex-column">
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="collapse" href="#item-1" style="color: #000;"><h5 align="center">Financeiro</h5></a>
			    <div id="item-1" class="collapse">
			      <ul class="nav flex-column ml-3">
			        <li class="nav-item">
			          <a class="nav-link active" href="#">Sub 1</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 2</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 3</a>
			        </li>
			      </ul>
			    </div>
			  </li>
			</ul>
	    </nav>
    </div>
    <div class="col-md-3">
		<nav class ="nav">
	      	<ul class="nav nav-pills flex-column">
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="collapse" href="#item-3" style="color: #000;"><h5 align="center">Vendas</h5></a>
			    <div id="item-3" class="collapse">
			      <ul class="nav flex-column ml-3">
			        <li class="nav-item">
			          <a class="nav-link active link" href="/pedido/novo">Novo Pedido</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 2</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 3</a>
			        </li>
			      </ul>
			    </div>
			  </li>
			</ul>
	    </nav>
    </div>
    <div class="col-md-3">
		<nav class ="nav">
			<ul class="nav nav-pills flex-column">
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="collapse" href="#item-5" style="color: #000;"><h5 align="center">Logistica</h5></a>
			    <div id="item-5" class="collapse">
			      <ul class="nav flex-column ml-3">
			        <li class="nav-item">
			          <a class="nav-link active" href="#">Sub 1</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 2</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link" href="#" style="color: #000;">Sub 3</a>
			        </li>
			      </ul>
			    </div>
			  </li>
			</ul>
	    </nav>
    </div>
    <div class="col-md-3">
		<nav class ="nav" align="center">
			<ul class="nav nav-pills flex-column">
			  <li class="nav-item">
			    <a class="nav-link" data-toggle="collapse" href="#item-7" style="color: #000;"><h5 align="center">Produtos</h5></a>
			    <div id="item-7" class="collapse">
			      <ul class="nav flex-column ml-3">
			        <li class="nav-item">
			          <a class="nav-link active link" href="/produto/all">Todos</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link link" href="/estoque/lancar" style="color: #000;">Lan. estoque</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link link" href="/marca/cadastrar" style="color: #000;">Cad. marca</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link link" href="/categoria/cadastrar" style="color: #000;">Cad. categoria</a>
			        </li>
			        <li class="nav-item">
			          <a class="nav-link link" href="/estoque/all" style="color: #000;">Vis. estoque</a>
			        </li>
			      </ul>
			    </div>
			  </li>
			</ul>
	    </nav>
    </div>
</div>