 desable-link<div class="container-fluid mt-5" id="starndarFooter" style="padding: 50px 20px;">
	<div class="row">
		<div class="col-11">
			<div class="row">
				<div class="col-md-3" style="padding: 5px 20px;">
					<h6>Conheça-nos</h6>
					<ul class="nav flex-column">
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Informações corporativas</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Carreiras</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Comunidade</a>
					    </li>
					</ul>
				</div>
				<div class="col-md-3" style="padding: 5px 20px;">
					<h6>Deixe-nos ajudá-lo</h6>
					<ul class="nav flex-column">
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Informações corporativas</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Carreiras</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Comunidade</a>
					    </li>
					</ul>
				</div>
				<div class="col-md-3" style="padding: 5px 20px;">
					<h6>Pagamento</h6>
					<ul class="nav flex-column">
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Informações corporativas</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Carreiras</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Comunidade</a>
					    </li>
					</ul>
				</div>
				<div class="col-md-3" style="padding: 5px 20px;">
					<h6>Trabalhe conosco</h6>
					<ul class="nav flex-column">
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Informações corporativas</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Carreiras</a>
					    </li>
					    <li class="nav-item">
					      <a class="nav-link desable-link" href="#">Comunidade</a>
					    </li>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-1" style="padding: 5px 20px;">
			<div class="row mb-2" style="justify-content: center;"><button class="btn midiasSociasis" ><i class="fab fa-facebook fa-2x"></i></button></div>
			<div class="row mb-2" style="justify-content: center;"><button class="btn midias midiasSociasis"><i class="fab fa-instagram fa-2x"></i></button></div>
			<div class="row mb-2" style="justify-content: center;"><button class="btn midiasSociasis" ><i class="fab fa-twitter fa-2x"></i></button></div>
			<div class="row" style="justify-content: center;"><button class="btn midias midiasSociasis"><i class="fab fa-whatsapp fa-2x"></i></button></div>
		</div>
		
	</div>
	<div class="row">
		<div class="col" align="center" style="color: #000;">&copy; <strong>Minha Empresa</strong> Todos os direitos rezervados</div>
	</div>
</div>