<div class="container-fluid container-md" id="menu-principal">
    <nav class="navbar">
        <div class="alinha-header">
            <div class="navbar-search" align="center" style="margin: auto;">
                <div class=""><a href="/" class="desable-link"><img src="../files/imagens/logo/logo_loja_option.png" style="width: 100px; height: 100px; position: absolute; top: 0; left: 0;" id='logo' alt="Minha loja.com"></a></div>
                <form class="navbar-form " id="form-header">
                    <div class="form-group div-search">
                        <input type="text" id="input-search" class="form-control" placeholder="Search">
                    </div>
                    <div class="form-group">
                         <button type="submit" class="btn btn-light">Buscar</button>
                    </div>
                </form>
            </div>
            <div class="login">
                <ul class="nav nav-tabs">
                    <li><a href="/pedido/carrinho/finsh" id="carrinhoLink" class="btn link desable-link"> <span style="font-size: 13px; color: #ffff;"><i class="fas fa-cart-plus fa-2x"></i></span><span  id="qtdItensCarrinho"><?php echo (isset($this->view->qtdItensCarrinho)) ? $this->view->qtdItensCarrinho: '';?></span></a></li>

                     <li class="nav-item dropdown" id="listLog">
                      <a class="dropdown-toggle desable-link" href="#" id="navLog" data-toggle="dropdown">
                        Seu login
                      </a>
                      <div class="dropdown-menu" herf="#navLog" >
                        <?php
                            if(isset($this->view->usuario) && (!empty($this->view->usuario ))){

                        ?>
                        <a class="dropdown-item desable-link" href="/home/login/logout" id="sair">Sair</a>
                        <a class="dropdown-item desable-link" href="/loja/painel" id="penelUser">Minha Conta</a>
                        <?php

                            }else{
                         ?>       
                          
                        <a class="dropdown-item desable-link" href="/home/login" id="entrar"  data-toggle="modal" data-target="#myModal">Entrar</a>
                        <?php
                          }
                        ?>
                        
                      </div>
                    </li>
                    <li><a href="#" class=" desable-link">Devoluções <span class="caret"></span></a></li>
                </ul>
            </div>
        </div>
        <div class="submenu">
            <ul class="nav nav-tabs" id="lista-submenu">
                <li class="nav-item"><a href="/produto/show" class="nav-link desable-link"> Mais Vendidos</a></li>
                <li class="nav-item"><a href="#" class="nav-link desable-link">Mais Desejados</a></li>
                <li class="nav-item"><a href="#" class="nav-link desable-link">Lançamentos</a></li>
                <li class="nav-item"><a href="#" class="nav-link desable-link">Ofertas do Dia</a></li>
                <li class="nav-item"><a href="#" class="nav-link desable-link">Atendimento ao Cliente</a></li>
                <li class="nav-item"><a href="/usuario/index" class="nav-link desable-link">link teste panel admin</a></li>
            </ul>
        </div>
    </nav>
</div>