<div class="container-fluid " id="menu-principal">
    <nav class="navbar">
        <div class="col-md-10 col-sm-6 col-xs-6">
            <div class="row">
                <div class="col-md-2 col-sm-12">
                    <a href="/" class="desable-link"><img src="../files/imagens/logo/logo_loja_option.png" id="logo-header"  alt="Minha loja.com" style=""></a>
                </div>
                <div class="col-md-10 col-sm-10" id="div-form-header">
                    <form class="row mt-3" style="width: 100%; margin: auto;" id="form-menu-header">
                        <div class="form-group col-10">
                            <input type="text" class="form-control form-control-md form-control-sm" placeholder="Search">
                        </div>
                        <div class="form-group col-2">
                             <button type="submit" class="btn btn-sm btn-light">Buscar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-sm-6 col-xs-6">
            <ul class="nav nav-tabs">
                <li><a href="/pedido/carrinho/finsh" id="carrinhoLink" class="btn link desable-link"> <span style="font-size: 13px; color: #ffff;"><i class="fas fa-cart-plus fa-2x"></i></span><span  id="qtdItensCarrinho"><?php echo (isset($this->view->qtdItensCarrinho)) ? $this->view->qtdItensCarrinho: '';?></span></a></li>

                 <li class="nav-item dropdown" id="listLog">
                  <a class="dropdown-toggle desable-link" href="#" id="navLog" data-toggle="dropdown">
                    Seu login
                  </a>
                  <div class="dropdown-menu" herf="#navLog" >
                    <?php
                        if(isset($this->view->usuario) && (!empty($this->view->usuario ))){

                    ?>
                    <a class="dropdown-item desable-link" href="/home/login/logout" id="sair">Sair</a>
                    <a class="dropdown-item desable-link" href="/loja/painel" id="penelUser">Minha Conta</a>
                    <?php

                        }else{
                     ?>       
                      
                    <a class="dropdown-item desable-link" href="/home/login" id="entrar"  data-toggle="modal" data-target="#myModal">Entrar</a>
                    <?php
                      }
                    ?>
                    
                  </div>
                </li>
            </ul>
        </div>
    </nav>
</div>