<nav class="navbar">
    <div class="container-fluid container-md navbar-dad">
        <div class="alinha-header">
            <div class="navbar-search">
                <button type="button" class="btn btn-default" id="button_menu">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                </button>
                <div class=""><img src="minha_loja.png" id='logo' alt="Minha loja.com"></div>
                <form class="navbar-form " id="form-header">
                    <div class="form-group div-search">
                        <input type="text" id="input-search" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Buscar</button>
                </form>
            </div>
            <div class="login">
                <ul class="nav navbar-nav nav-tabs">
                    <li><a href="#" class="btn"> <span style="font-size: 13px; color: #ffff;"><i class="fas fa-cart-plus fa-2x"></i></i></span></a></li>
                    <li><a href="/home/login" class="link">Seu login <span class="caret"></span></a></li>
                    <li><a href="#" class="link">Devoluções <span class="caret"></span></a></li>
                </ul>
            </div>
        </div>
        <div class="submenu">
            <div class="submenu_esquerdo">
                <ul class="nav navbar-nav list-inline">
                    <li><a href="#"> Mais Vendidos</a></li>
                    <li><a href="#">Mais Desejados</a></li>
                    <li><a href="#">Lançamentos</a></li>
                    <li><a href="#">Ofertas do Dia</a></li>
                    <li><a href="#">Atendimento ao Cliente</a></li>
                </ul>
            </div>
            <div class="submenu_direito">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
</nav>