<div class="row" style="background-color: #fff; width: 100%;  margin: auto;" align="left">
	<div class="col py-3">
		<div class="row mb-2"><div class="col" id="msg-logradouro"></div></div>
		<div class="row mb-4">
			<div class="col h4" style="width: 80%;" align="center"><strong>Atualizar cadastro</strong></div>
		</div>
		<div class="row">
			<form method="post" id="cadastro-pessoa-atualizar" action="/pessoa/atualizar" enctype="multipart/form-data" style="margin: auto; width: 80%;">
				<input type="hidden" name="cd" value="<?=$this->view->registros->getIdPessoa();?>">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="nome">Nome</label>
							<input type="text" minlength="4" maxlength="200" name="nome" id="nome" class="form-control form-control-sm" value="<?=$this->view->registros->getNomePessoa(); ?>"placeholder="Seu primeiro nome" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="nome_complementar">Sobrenome</label>
							<input type="text" minlength="4" maxlength="200" placeholder="Seu segundo nome" name="nome_complementar" id="nome_complementar" class="form-control form-control-sm" value="<?=$this->view->registros->getNomeComplementar();?>" required="required">
						</div>
					</div>
					
				</div>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="documento">Cpf</label>
							<input type="text" minlength="11" maxlength="11" placeholder="CPF com 11 dígitos" name="documento" id="documento" class="form-control form-control-sm" value="<?=$this->view->registros->getDocumento();?>" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="documento_complementar">RG</label>
							<input type="text" minlength="13" maxlength="13" placeholder="Rg com 13 dígitos" name="documento_complementar" id="documento_complementar" class="form-control form-control-sm" value="<?=$this->view->registros->getDocumentoComplementar();?>" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="sexo">Sexo</label>
							<select name="sexo" id="sexo" class="form-control form-control-sm" required="required">
								<option <?=($this->view->registros->getSexo() == 'M') ? 'selected' : '';?> value="M">Masculino</option>
								<option  <?=($this->view->registros->getSexo() == 'F') ? 'selected' : '';?> value="F">Feminino</option>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="img">Imagem</label>
							<input type="file" name="img" id="img" class="form-control form-control-sm" value="<?=$this->view->registros->getImg();?>">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="login">Email</label>
							<input placeholder="exemplo@gmail.com" type="email" name="login" id="" class="form-control form-control-sm" value="<?=$this->view->registros->getLogin();?>" maxlength="100" minlength="12" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="senha">Senha</label>
							<input type="text" placeholder="Senha com pelomenos 9 dígitos" minlength="9" maxlength="12" name="senha" id="senha" class="form-control form-control-sm" >
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col" align="left">
						<button type="submit" class="btn btn-sm btn-primary">Atualizar</button>
						<a align='right' href="/" id="cancelar" class="btn btn-sm btn-danger">Cancelar</a>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>