<div class="container-fluid">
  <div class="row pt-5">
    <div class="col-ms-6 col-md-8">
      <div class="row">
        <div class="col">
          <form class="form-row">
            <div class="form-group mr-2">
              <label for="vendedor"><strong>Vendedor: </strong></label>
              <input type="text" name="vendedor" class="form-control" id="vendedor">
            </div>
            <div class="form-group mr-2">
              <label for="pedido"><strong>Pedido: </strong></label>
              <input type="text" name="pedido" class="form-control" id="pedido">
            </div>
            <div class="form-group mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control" id="cliente">
            </div>
            <div class="form-group pt-2">
              <button class="btn btn-success mt-4">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col">          
         <table class="table table-hover">
           <thead>
             <tr>
               <th>Data</th>
               <th>Nº Pedido</th>
               <th>Cliente</th>
               <th>Vendedor</th>
               <th>Vl. Pedido</th>
             </tr>
           </thead>
           <tbody>
             <?php
                if(isset($this->view->prevendas) && (is_array($this->view->prevendas))){
                  for ($i=0; !($i == count($this->view->prevendas)); $i++) { 
                  
             ?>
               <tr>
                  <td><?=$this->view->prevendas[$i]->dtPedido;?></td>
                  <td><?=$this->view->prevendas[$i]->idPedido;?></td>
                  <td><?=$this->view->prevendas[$i]->cliente;?></td>
                  <td><?=$this->view->prevendas[$i]->vendedor;?></td>
                  <td><?=number_format($this->view->prevendas[$i]->total, 2, ',', '.');?></td>
               </tr>
             <?php 
                # code...
                  }
                }
             ?>
           </tbody>
         </table>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4 mt-4">
      <div class="row">
        <div class="col-sm-2 col-md-2">
          <strong>Desdobrados:</strong>
        </div>
        <div class="col">
          <form class="form-row ml-5">
            <div class="form-group ml-4 mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control" id="cliente">
            </div>
            <div class="form-group pt-2">
              <button class="btn btn-success mt-4">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
       <div class="col">
         <table class="table table-hover">
           <thead>
             <tr>
               <th>Data</th>
               <th>Nº Pedido</th>
               <th>Cliente</th>
               <th>Vendedor</th>
               <th>Vl. Pedido</th>
             </tr>
           </thead>
           <tbody>
             
           </tbody>
          </table>
       </div>
      </div>
      <div class="row mt-5">
        <div class="col-sm-2 col-md-2">
          <strong>Print:</strong>
        </div>
        <div class="col" align="rigth">
          <form class="form-row ml-5">
            <div class="form-group ml-4 mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control" id="cliente">
            </div>
            <div class="form-group pt-2">
              <button class="btn btn-success mt-4">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <table class="table table-hover">
             <thead>
               <tr>
                 <th>Data</th>
                 <th>Nº Pedido</th>
                 <th>Cliente</th>
                 <th>Vendedor</th>
                 <th>Vl. Pedido</th>
               </tr>
             </thead>
             <tbody>
               
             </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>