
<div class="row" id="row-nav">
  <div class="col-md-12">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-1">
          <button type="button" class="btn btn-success mt-2" id="controlNavPanel">
            <i class="fas fa-minus" id="ic"></i>
          </button>
        </div>
        <div class="col-md-11">
          <nav class="navbar navbar-expand-sm justify-content-center pt-2 pb-2 pl-2 pr-2" id="navPanelCliente">
            <ul class="navbar-nav" >
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pinpad/index" id="panelPedidoInicio">Inicio</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/pedidos?cliente=<?=$this->view->idCliente?>" id="panelPedidoPedidos">Transações</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/financeiro?cliente=<?=$this->view->idCliente?>" id="panelPedidoInfoFinan">Movimentações</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/prevendas?cliente=<?=$this->view->idCliente?>" id="panelPedidoPrevendas">Abert. / Fechamento Caixa</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/orcamentos?cliente=<?=$this->view->idCliente?>" id="panelPedidoOrcamentos">Orçamentos</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/cadastro?cliente=<?=$this->view->idCliente?>" id="panelPedidoCadastro">Pedidos</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/compras?cliente=<?=$this->view->idCliente?>" id="panelPedidoUltCompras">Prevendas</a>
              </li>
              <li class="nav-item" style="margin: auto;">
                <a class="pt-2 pb-2 pl-2 pr-2 btn link" href="/pessoa/nfs?cliente=<?=$this->view->idCliente?>"  id="panelPedidoNfs">Nf's</a>
              </li>
              <li class="nav-item dropdown" style="margin: auto;">
                <a class="dropdown-toggle btn link-panel-cliente" href="#" id="navbardrop" data-toggle="dropdown">
                  Mais opções
                </a>
                <div class="dropdown-menu" herf="#navbardrop" >
                  <a class="dropdown-item" href="#">Link 1</a>
                  <a class="dropdown-item" href="#">Link 2</a>
                  <a class="dropdown-item" href="#">Link 3</a>
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row py-5">
    <div class="col-ms-6 col-md-7">
      <div class="row">
        <div class="col">
          <form class="form-row">
            <div class="form-group mr-2">
              <label for="vendedor"><strong>Vendedor: </strong></label>
              <input type="text" name="vendedor" class="form-control form-control-sm" id="vendedor">
            </div>
            <div class="form-group mr-2">
              <label for="pedido"><strong>Pedido: </strong></label>
              <input type="text" name="pedido" class="form-control form-control-sm" id="pedido">
            </div>
            <div class="form-group mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control form-control-sm" id="cliente">
            </div>
            <div class="form-group">
              <button class="btn btn-sm btn-success" style="margin-bottom: -70px;">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col" style="height: 35rem; overflow-y: auto;">          
         <table class="table table-hover">
           <thead>
             <tr>
                <th>Mult.</th>
                <th>Data</th>
                <th>Nº Pedido</th>
                <th>Cliente</th>
                <th>Vendedor</th>
                <th>Vl. Pedido</th>
             </tr>
           </thead>
           <tbody>
             <?php
                if(isset($this->view->prevendas) && (is_array($this->view->prevendas))){
                  for ($i=0; !($i == count($this->view->prevendas)); $i++) { 
                  
             ?>
               <tr>
                  <td>
                    <div class="form-group">
                      <input type="checkbox" class="form-control-sm" value="<?=$this->view->prevendas[$i]->dtPedido;?>" name="prod-<?=$this->view->prevendas[$i]->dtPedido;?>">
                    </div>
                  </td>
                  <td><?=$this->view->prevendas[$i]->dtPedido;?></td>
                  <td><?=$this->view->prevendas[$i]->idPedido;?></td>
                  <td><?=$this->view->prevendas[$i]->cliente;?></td>
                  <td><?=$this->view->prevendas[$i]->vendedor;?></td>
                  <td><?=number_format($this->view->prevendas[$i]->total, 2, ',', '.');?></td>
               </tr>
             <?php 
                # code...
                  }
                }
             ?>
           </tbody>
         </table>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-5 mt-4">
      <div class="row">
        <div class="col-sm-2 col-md-2">
          <strong>Desdobrados:</strong>
        </div>
        <div class="col-sm-10 col-md-10">
          <form class="form-row" style="float: right;">
            <div class="form-group ml-4 mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control form-control-sm" id="cliente">
            </div>
            <div class="form-group">
              <button class="btn btn-sm btn-success" style="margin-bottom: -70px;">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
       <div class="col">
         <table class="table table-hover">
           <thead>
             <tr>
               <th>Data</th>
               <th>Nº Pedido</th>
               <th>Cliente</th>
               <th>Vendedor</th>
               <th>Vl. Pedido</th>
             </tr>
           </thead>
           <tbody>
             
           </tbody>
          </table>
       </div>
      </div>
      <div class="row mt-5">
        <div class="col-sm-2 col-md-2">
          <strong>Print:</strong>
        </div>
        <div class="col" align="rigth">
           <form class="form-row" style="float: right;">
            <div class="form-group ml-4 mr-2">
              <label for="cliente"><strong>Cliente: </strong></label>
              <input type="text" name="cliente" class="form-control form-control-sm" id="cliente">
            </div>
            <div class="form-group">
              <button class="btn btn-sm btn-success" style="margin-bottom: -70px;">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <table class="table table-hover">
             <thead>
               <tr>
                 <th>Data</th>
                 <th>Nº Pedido</th>
                 <th>Cliente</th>
                 <th>Vendedor</th>
                 <th>Vl. Pedido</th>
               </tr>
             </thead>
             <tbody>
               
             </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>