<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<form method="post" class="was-validated" action="/produto/salvar" enctype="multipart/form-data">
			<fieldset class=""><legend><strong>Nova venda</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label for="idCliene">Cliente:</label>
									<input value="" type="text" name="cliente" id="idCliene" class="form-control" placeholder="Nome, CPF ou CNPJ" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<label for="idRepresentante">Representante:</label>
								<input value="" type="text" name="representante" id="idRepresentante" class="form-control" placeholder="Nome Representante" required="required">
							</div>
							<div class="col-md-6">
								<label for="idTipoContato">Tipo contato:</label>
								<select name="contato" id="idTipoContato" class="form-control" required="required">
									<option>Presencial</option>
									<option>Telefone</option>
									<option>Email</option>
								</select>
							</div>
						</div>
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
						<div class="row">
							<h3 align="center">Observações:</h3>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Iniciar</button>  <a href="/produto/all" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>
	</div>
</div>