
<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-sm justify-content-center pt-2 pb-2 pl-2 pr-2" id="navPanelCliente">
			  <ul class="navbar-nav" >
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 1</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 2</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-2 pb-2 pl-2 pr-2" href="#">Link 3</a>
			    </li>
			    <li class="nav-item dropdown" style="margin: auto;">
			      <a class="dropdown-toggle link" href="#" id="navbardrop" data-toggle="dropdown">
			        Dropdown link
			      </a>
			      <div class="dropdown-menu" herf="#navbardrop" >
			        <a class="dropdown-item" href="#">Link 1</a>
			        <a class="dropdown-item" href="#">Link 2</a>
			        <a class="dropdown-item" href="#">Link 3</a>
			      </div>
			    </li>
			  </ul>
			</nav>
			<div class="row mt-3">
				<div class="col-md-4">
					<span><strong>Cliente: </strong> <?=$this->view->cliente?></span>
				</div>
				<div class="col-md-4">
					<span><strong>CPF: </strong></span>
				</div>
				<div class="col-md-4">
					<span><strong>Endereço entrega: </strong></span>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row" style="padding: 20px 40px;">
	<div class="col-md-8">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="vendaPainelTable">
			<fieldset class=""><legend><strong>Pedido:</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-12" style="height: 380px;  overflow: auto;">
								<table class="table table-dark table-hover mb-2">
									<thead>
										<tr>
									        <th>Pdoduto</th>
									        <th>Qtd</th>
									        <th>Peço</th>
									        <th>Desconto</th>
									        <th>Total deconto</th>
									        <th>Peço com desconto</th>
									        <th>Subtotal</th>
									        <th>Ação</th>
									    </tr>
								    </thead>
								    <tbody>
								    	<tr id="trMsg">
								    		<td colspan="8">
								    			<div class="row" style="">
								    				<div class="col-md-12 alert alert-warning">
								    					<h3 align="center">Adicione produtos para começar!</h3>
								    				</div>
								    			</div>
								    		</td>
								    	</tr>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<div class="form-group mt-2">
									<label for=""><strong>Formas de pagamento: </strong></label><br>
									<button class="btn btn-success">CCR</button>
									<button class="btn btn-success">CD</button>
									<button class="btn btn-success">BOL</button>
									<button class="btn btn-success">NP</button>
									<button class="btn btn-success">CDC</button>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<strong>Total geral: R$ <span id="totGeralVenda" ></span> </strong>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<button id="idFilanizar" class="btn btn-primary">Finalizar</button>
								<a href="/venda/nova"class="btn btn-danger link">Cancelar</a>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	<div class="col-md-4">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="serchProd">
			<fieldset class=""><legend><strong>Buscar produto:</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="loadCodProd"><strong>Cod:</strong></label>
									<input  type="text" name="loadCodProd" id="loadCodProd" class="form-control">
								</div>
							</div>
							<div class="col-md-8">
								<div class="form-group">
									<label for="loadProduto"><strong>Produto:</strong></label>
									<input  type="text" name="loadProduto" id="loadProduto" class="form-control" placeholder="Nome do produto">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<table class="table table-dark table-hover" id="tableSearch">
									<thead>
										<tr>
											<th>Cod</th>
									        <th>Produto</th>
									        <th>Preço</th>
									        <th>Estoque</th>
									    </tr>
								    </thead>
								    <tbody>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-8">
								<div class="form-group">
									<label for="qtdProduct"><strong>Quantidade:</strong></label>
									<input type="number" name="qtdProduct" id="qtdProduct" class="form-control" >
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="descPercent"><strong>Desconto %:</strong></label>
									<input type="text" name="descPercent" id="descPercent" class="form-control" >
								</div>
							</div>
						</div>
					</div>
				</div>
				<button id="idAdicionar" class="btn btn-primary">Adicionar</button>
			</fieldset>
		</form>
	</div>
</div>