<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-sm justify-content-center" id="navPanelCliente">
			  <ul class="navbar-nav" >
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 1</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 2</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item dropdown" style="margin: auto;">
			      <a class="dropdown-toggle link" href="#" id="navbardrop" data-toggle="dropdown">
			        Dropdown link
			      </a>
			      <div class="dropdown-menu" herf="#navbardrop" >
			        <a class="dropdown-item" href="#">Link 1</a>
			        <a class="dropdown-item" href="#">Link 2</a>
			        <a class="dropdown-item" href="#">Link 3</a>
			      </div>
			    </li>
			  </ul>
			</nav>
		</div>
	</div>
</div>
<div class="row" style="padding: 20px 40px;">
	<div class="col-md-8">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="vendaPainel">
			<fieldset class=""><legend><strong>Pedido:</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-12">
								<table class="table table-dark table-hover">
									<thead>
										<tr>
									        <th>Pdoduto</th>
									        <th>Qtd</th>
									        <th>Peço</th>
									        <th>Desconto</th>
									        <th>Peço com desconto</th>
									        <th>Tot. com desconto</th>
									        <th>Subtotal</th>
									        <th>Ação</th>
									    </tr>
								    </thead>
								    <tbody>
								    	<tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
									    <tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
									    <tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
									    <tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
									    <tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
									    <tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									        <td>5,20</td>
									        <td>150,00</td>
									        <td>122,20</td>
									        <td>1.785,02</td>
									        <td> 
									        	<a href="/produto/editar?id=" class="btn btn-success mr-2">
													<i class="fas fa-pencil-alt"></i>
												</a>
												<a href="/produto/excluir?id=" class="btn btn-danger">
													<i class="fas fa-trash-alt"></i>
												</a>
									        </td>
									    </tr>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label for="totGelaVenda">Total geral: </label>
									<span id="totGeralVenda" class="form-control"></span>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<button id="idFilanizar" class="btn btn-primary">Finalizar</button>
								<a href="/venda/nova"class="btn btn-danger link">Cancelar</a>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	<div class="col-md-4">
		<form method="post" class="was-validated" action="/venda/produto/search" enctype="multipart/form-data" id="serchProd">
			<fieldset class=""><legend><strong>Buscar produto:</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="loadCodProd">Cod:</label>
									<input value="" type="text" name="loadCodProd" id="loadCodProd" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-8">
								<div class="form-group">
									<label for="loadProduto">Produto:</label>
									<input value="" type="text" name="loadProduto" id="loadProduto" class="form-control" placeholder="Nome do produto" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<table class="table table-dark table-hover" id="tableSearch">
									<thead>
										<tr>
									        <th>Pdoduto</th>
									        <th>Peço</th>
									        <th>Estoque</th>
									    </tr>
								    </thead>
								    <tbody>
								    	<tr>
									        <td>Not book</td>
									        <td>2</td>
									        <td>2.500,00</td>
									    </tr>
								    </tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="qtdProduct">Quantidade:</label>
									<input value="" type="text" name="qtdProduct" id="qtdProduct" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="descPercent">Desconto %:</label>
									<input value="" type="text" name="descPercent" id="descPercent" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="descDin">Desconto R$:</label>
									<input value="" type="text" name="descDin" id="descDin" class="form-control" required="required">
								</div>
							</div>
						</div>
					</div>
				</div>
				<button id="idFilanizar" class="btn btn-primary">Adicionar</button>
			</fieldset>
		</form>
	</div>
</div>