<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-sm justify-content-center" id="navPanelCliente">
			  <ul class="navbar-nav" >
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 1</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 2</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item" style="margin: auto;">
			      <a class="pt-4 pb-4 pl-4 pr-4" href="#">Link 3</a>
			    </li>
			    <li class="nav-item dropdown" style="margin: auto;">
			      <a class="dropdown-toggle link" href="#" id="navbardrop" data-toggle="dropdown">
			        Dropdown link
			      </a>
			      <div class="dropdown-menu" herf="#navbardrop" >
			        <a class="dropdown-item" href="#">Link 1</a>
			        <a class="dropdown-item" href="#">Link 2</a>
			        <a class="dropdown-item" href="#">Link 3</a>
			      </div>
			    </li>
			  </ul>
			</nav>
		</div>
	</div>
</div>
<div class="row" style="padding: 20px 40px;">
	<div class="col">
		<br/>
		<br/>
		afafaf
		<br/>
		<br/>
	afafaf
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		<br/>
		afafaf
		<br/>
		<br/>
		<br/>
		afafaf
		<br/>
		<br/>
		<br/>,
		afafaf
		<br/>
		<br/>
		<br/>
		afafaf
		<br/>
		<br/>
		<br/>,
	</div>
</div>