<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<form method="post" id="editEstoque" class="was-validated" action="/estoque/atualizar" enctype="multipart/form-data">
			<input type="hidden" name="fornecimento" value="<?=$this->view->result->getIdFornecimento();?>">
			<fieldset class=""><legend><strong>Editar estoque</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="idProduto">Produto:</label>
									<select name="produto" id="idProduto" class="form-control" placeholder="Nome , Codigo" required="required">
										<?php
											for ($i=0; !($i == count($this->view->resultProduto)); $i++) { 
												
												$selected = ($this->view->resultProduto[$i]->getIdProduto() == 
													$this->view->result->ProdutoIdProduto) ?'selected="selected"': '';
											

										 ?>
											<option <?=$selected?> value="<?=$this->view->resultProduto[$i]->getIdProduto(); ?>"><?= $this->view->resultProduto[$i]->getNomeProduto();?></option>

										<?php

											}
										 ?>
									</select>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="idFor">Fornecedor:</label>
									<select name="fornecedor" id="idFor" class="form-control" placeholder="Nome , Codigo" required="required">
										<option>Fornecedor tal</option>
									</select>
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-3">
								<div class="form-group">
									<label for="idValidade">Data validade:</label>
									<input value="<?=substr($this->view->result->getDataValidade(), 0, 10);?>" type="date" name="dtValidade" id="idValidade" class="form-control" equired="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="dtFornecimento">Data fornecimento:</label>
									<input value="<?=substr($this->view->result->getDataFornecimento(), 0, 10)?>" type="date" name="dtFornecimento" class="form-control"  id="dtFornecimento" required="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="dtRecebimento">Data recebimento:</label>
									<input value="<?= substr($this->view->result->getDataRecebimento(), 0, 10)?>" type="date" name="dtRecebimento" class="form-control" id="dtRecebimento" required="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="qtd">Quantidade:</label>
									<input value="<?=$this->view->result->getQtdFornecida();?>" type="number" class="form-control" name="qtd" id="qtd">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="vlCompra">Valor compra:</label>
									<input value="<?=$this->view->result->getValCompra();?>" type="number" name="vlCompra" id="vlCompra" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="margemPretend">Margem pretendida %:</label>
									<input value="<?=0?>" type="number" name="margem" id="margemPretend" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="vlVenda">Valor Venda:</label>
									<input vvalue="<?=0?>" type="number" name="vlVenda" id="vlVenda" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<label for="idNF">Nota fiscal:</label>
								<input value="<?=$this->view->result->getNotaFiscal();?>" type="number" name="nf" id="idNF" class="form-control" required="required">
							</div>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Lançar</button>  <a href="/estoque/all" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>
	</div>
</div>