<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<?php
			if($this->view->produtos == false){


		 ?>
			<div class="row">
				<div class="col-md-11">
					<h4><strong>Novo estoque</strong></h4>
				</div>
				<div class="col-md-1">
					<a href="/produto/cadastrar" class="btn btn-success mb-2" id="cadastrar">
						<i class="fas fa-plus-circle fa-2x"></i>
					</a>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 alert alert-warning">
					<h2 align="center">Comece adinionando novos produtos clicando no botão acima!</h2>
				</div>
			</div>

		 <?php

			}else{

		  ?>
		<form method="post" id="estoque" class="was-validated" action="/estoque/salvar" enctype="multipart/form-data">
			<fieldset class=""><legend><strong>Novo estoque</strong></legend>
				<div class="row mb-4">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="idProduto">Produto:</label>
									<select name="produto" id="idProduto" class="form-control" placeholder="Nome , Codigo" required="required">
										<?php
											for ($i=0; !($i == count($this->view->produtos)); $i++) { 
												# code...
											

										 ?>
											<option value="<?=$this->view->produtos[$i]->getIdProduto(); ?>"><?= $this->view->produtos[$i]->getNomeProduto();?></option>

										<?php

											}
										 ?>
									</select>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="idFor">Fornecedor:</label>
									<select name="fornecedor" id="idFor" class="form-control" placeholder="Nome , Codigo" required="required">
										<option>Fornecedor tal</option>
									</select>
								</div>
							</div>
							
						</div>
						<div class="row">
							<div class="col-md-3">
								<div class="form-group">
									<label for="idValidade">Data validade:</label>
									<input value="" type="date" name="dtValidade" id="idValidade" class="form-control" equired="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="dtFornecimento">Data fornecimento:</label>
									<input type="date" name="dtFornecimento" class="form-control"  id="dtFornecimento" required="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="dtRecebimento">Data recebimento:</label>
									<input type="date" name="dtRecebimento" class="form-control" id="dtRecebimento" required="required">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label for="qtd">Quantidade:</label>
									<input type="number" class="form-control" name="qtd" id="qtd">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label for="vlCompra">Valor compra:</label>
									<input value="" type="number" name="vlCompra" id="vlCompra" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="margemPretend">Margem pretendida %:</label>
									<input value="" type="number" name="margem" id="margemPretend" class="form-control" required="required">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label for="vlVenda">Valor Venda:</label>
									<input value="" type="number" name="vlVenda" id="vlVenda" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<label for="idNF">Nota fiscal:</label>
								<input value="" type="number" name="nf" id="idNF" class="form-control" required="required">
							</div>
						</div>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Lançar</button>  <a href="/produto/all" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>

		<?php

			}
		 ?>
	</div>
</div>