<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<?php
		
			if(($this->view->categorias == 0) || ($this->view->marcas == 0)){


		 ?>
		 	<div class="row">
		 		<div class="col-md-12">
		 			<h4><strong>Cadastrar produto</strong></h4>
		 		</div>
		 	</div>
			<div class="row">
				<div class="col-md-12 alert alert-warning">
					<h2 align="center">Comece adicionando novas marcas e categorias!</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-11" align="">
					<a href="/marca/cadastrar" class="btn btn-primary link">Add Marcas</a>
					<a href="/categoria/cadastrar" class="btn btn-primary link">Add Categorias</a>
					<a href="/produto/all" class="btn link ml-2 btn-danger">Cancelar</a>
				</div>
			</div>

		 <?php
			}else{
		 ?>
		<form method="post" class="was-validated formAjax" action="/produto/salvar" enctype="multipart/form-data" style="" id="cadastrarProduto">
			<fieldset class=""><legend><strong>Cadastrar produto</strong></legend>
				<div class="row">
					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idNome">Nome</label>
									<input type="text" name="nome" id="idNome" class="form-control" placeholder="Nome do produto" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<div class="form-group">
										<label for="idMarc">Marca: </label>
										<select class="form-control " id="idMarc" name="marca" required="required">
											<?php 
											for ($i=0; !($i == count($this->view->marcas)) ; $i++) { 
												
										?>
											<option value="<?= $this->view->marcas[$i]->getIdMarca()?>" ><?= $this->view->marcas[$i]->getNomeMarca()?></option>
										<?php 
											}
										?>
										</select>
									</div>
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<div class="form-group">
										<label for="idMsg">Imgem do produto: </label>
										<input type="file" class="form-control" id="upload" name="imgProduto" required="required">
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idCategoria">Categoria: </label>
									<select class="form-control " id="idCategoria" name="categoria[]" multiple size="3" required="required">
										<?php 
											for ($i=0; !($i == count($this->view->categorias)) ; $i++) { 
												
										?>
											<option value="<?= $this->view->categorias[$i]->getIdCategoria()?>" ><?= $this->view->categorias[$i]->getCategoria()?></option>
										<?php 
											}
										?>
									</select>
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idTexto">Texto promorcional:</label>
									<textarea class="form-control" name="texto" rows="2" id="idTexto" required="required"></textarea>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="form-group form-check">
									<label class="form-check-label" for="idSobrescrever" style="margin-right: 25px;">Sobrescrever imagem no destino?</label>
									<input class="form-check-input" type="checkbox" name="sobrescrever" id="idSobrescrever"></input>
								</div>
							</div>
						</div>
					</div>	
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="containerImg">
						<img id="img"/>
					</div>	
				</div>
				<button type="submit" class="btn btn-primary">Cadastrar</button> <a href="/produto/all" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>
		</form>

		<?php
			}
		?>
	</div>
</div>