<div class="container-fluid standard-background"  style="height: 100%;">
	<div class="container">
		<form method="post" class="was-validated" action="/produto/salvar" enctype="multipart/form-data"  style="padding: 34px 40px;">
			<fieldset class=""><legend><strong>Lançar produto</strong></legend>
				<div class="row">
					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idNome">Nome</label>
									<input type="text" name="nome" id="idNome" class="form-control" placeholder="Nome do produto" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idNf">Nº NF</label>
									<input type="number" name="nf" id="idNf" class="form-control" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idQuantidade">Quantidade</label>
									<input type="number" name="estoque" id="idQuantidade" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idSescricao">Descricao</label>
									<input type="text" name="descricao" id="idSescricao" class="form-control" placeholder="Descricão do produto" required="required">
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-66">
								<div class="form-group">
									<label for="idFornecedor">Fornecedor: </label>
									<input type="text" name="nf" id="idFornecedor" placeholder="Nome do fornecedor" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idCodigo">Código do produto</label>
									<input type="text" name="codigo" id="idCodigo" class="form-control" placeholder="Código do produto" required="required">
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<div class="form-group">
										<label for="idMsg">Imgem do produto: </label>
										<input type="file" class="form-control" id="upload" name="imgProduto" required="required">
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<div class="form-group">
										<label for="idMarc">Marca: </label>
										<select class="form-control " id="idMarc" name="marca" required="required">
											<?php 
											for ($i=0; !($i == count($this->view->marcas)) ; $i++) { 
												
										?>
											<option value="<?= $this->view->marcas[$i]->getIdMarca()?>" ><?= $this->view->marcas[$i]->getMarca()?></option>
										<?php 
											}
										?>
										</select>
									</div>
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idCategoria">Categoria: </label>
									<select class="form-control " id="idCategoria" name="categoria" multiple size="3" required="required">
										<?php 
											for ($i=0; !($i == count($this->view->categorias)) ; $i++) { 
												
										?>
											<option value="<?= $this->view->categorias[$i]->getIdCategoria()?>" ><?= $this->view->categorias[$i]->getCategoria()?></option>
										<?php 
											}
										?>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="form-group">
									<label for="idTexto">Texto promorcional:</label>
									<textarea class="form-control" name="texto" rows="6" id="idTexto"></textarea>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="form-group form-check">
									<label class="form-check-label" for="idSobrescrever" style="margin-right: 25px;">Sobrescrever imagem no destino?</label>
									<input class="form-check-input" type="checkbox" name="sobrescrever" id="idSobrescrever"></input>
								</div>
							</div>
						</div>
					</div>	
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="containerImg">
						<img id="img"/>
					</div>	
				</div>
				<button type="submit" class="btn btn-lg btn-success">Lançar</button> 
			</fieldset>

		</form>
	</div>
</div>