
<div class="container-fluid py-3" id="detalheProduto" style="">
	<?php
		if((isset($this->view->qtdSaldo)) && ($this->view->qtdSaldo == 0)){
	?>
	<div class="row">
		<div class="col alert alert-warning text-center h2"><strong>Atenção: </strong> Item sem estoque!</div>
	</div>
	<?php
		}
	?>
	<div class="row" style="width: 80%; margin:auto;">
		<div class="col-md-5 col-sm-6 mb-5  mt-3" align="center" id="imgP">
				<img id="<?=$this->view->produto->getIdProduto();?>"  class="img-produto" src="../files/imagens/<?=$this->view->imagensProduto[0]->getUrl();?>" style="width: 75%; height: 75%;" data-zoom-image="../files/imagens/<?=$this->view->imagensProduto[0]->getUrl();?>"><br><br>
			<div id="gali">
			<?php
				for ($i=0, $imagens = $this->view->imagensProduto;!($i == count($imagens)) ; $i++) { 
					# code...
				
			 ?>
			 		<a href="#" data-image="../files/imagens/<?=$imagens[$i]->getUrl();?>" data-zoom-image="../files/imagens/<?=$imagens[$i]->getUrl();?>">
					    <img class="img-produto-opt" src="../files/imagens/<?=$imagens[$i]->getUrl();?>" style="width: 100px;">

					 </a>
			 		
			 	
			 <?php 
			 	}
			 ?>
			 </div>
			 <div class="row">
			 	<div class="col" align="left">
			 		<div class="row">
			 			<div class="col">
			 				Deixe seu like
			 			</div>
			 		</div>
			 		<div class="row ">
			 			<div class="col">
			 				<div id="barra">
				 				<span class="bg" style="width:0"></span>
					 			<div class=" estrelas">
					 				<?php for ($i=0; !($i == 5); $i++):?>
					 					<span class="star" id="<?=$i?>">
					 						<span class="starAbsolute"></span>
					 					</span>
					 				<?php endfor;?>
					 			</div>
					 		</div>
			 			</div>
			 		</div>
			 	</div>
			 </div>
	 		<div class="row my-5" style="clear: both;" align="left">
	 			<div class="col text-success" id="response">
	 				<div class="row">

	 				</div>
	 			</div>
	 		</div>
		</div>
		<div class="col-md-5  col-sm-6  mt-3" align="left" style="clear: both;">
			<h4><strong><?=$this->view->produto->getNomeProduto();?></strong></h4>
			<p>
				<div class="row">
		 			<div class="col">
		 				<div id="barra-detalhes" class="row">
			 				<span class="bg-detalhes" style="width: <?=$this->view->percent?>"></span>
				 			<div class=" estrelas-detalhes">
				 				<?php for ($i=0; !($i == 5); $i++):?>
				 					<span class="star-detalhes" id="<?=$i?>">
				 						<span class="starAbsolute-detalhes"></span>
				 					</span>
				 				<?php endfor;?>
				 			</div>
				 		</div>
		 			</div>
		 		</div>

			</p>
			<p  class="mt-5" style="font-weight: bolder;"><sup>Por: </sup><span>R$ </span><span id="vlP"><?= number_format($this->view->fornecimento->getVlVenda(), 2, ',','.') ?></span></p>
			<hr align="left" width="50%;" />
			<h4>Detalhes do produto</h4>
			<p>Cor:</p>
			<p>Altura:</p>
			<p>Largura:</p>
			<p>Comprimento:</p>
			<p>Número do modelo</p>
			<p>Código de barras:</p>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</div>
		<div class="col-md-2 col-sm-12" align="center">
			<div class="row my-4">
				<div class="col">
					Compartilhe <a href="" class="mx-1"><i class="fab fa-whatsapp fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-twitter fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-instagram fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-facebook fa-1x"></i></a>
				</div>
			</div>
			<div class="row" style="box-shadow: 1px 1px 2px #000">
				<div class="col">
					<form class="py-4" method="post" action="/pedido/produto/frete" id="formFretQtd">
						<input type="hidden" name="prod" value="<?=$this->view->produto->getIdProduto();?>">
						<div class="form-group row">
							<div class="col" align="left">
								<label for="qtd"><strong>Quantidade</strong></label>
							</div>
							<div class="col">
								<select class="form-control" id="qtd" name="qtd">
									<?php
										if((isset($this->view->qtdSaldo)) && ($this->view->qtdSaldo >= 4)){
									?>
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<?php

										}else{
											for($i=0; !($i== $this->view->qtdSaldo); $i++){
									?>

									<option value="<?=$i+1?>"><?=$i+1?></option>
									<?php
											}

										}
									?>
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col">
								<button class="btn btn-warning" type="button" id="btnAddCarr"><strong>Add. Carrinho</strong></button>
							</div>
						</div>
						<div class="form-group row">
							<div class="col">
								<button class="btn btn-warning" type="button" id="compNow" ><strong>Compar Agora</strong></button>
							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="left">
								<p><strong>Sua compra é <a href="#" class="text-success">segura</a></strong></p>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-sm-3" align="left">
								<label for="frete"><strong>Calc. Frete</strong></label>
							</div>
							<div class="col-sm-9">
								<input type="text" placeholder="CEP" name='cep' class="form-control" id="frete"/><br>

							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="center" id="response">
							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="center">
								<button class="btn btn-success" id="calcularFrete"><strong>Calcular</strong></button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
	<div class="row" style="width: 80%; margin:auto;">
		<div class="col">
			<?php

				if(isset($this->view->othesFornecimentosPrim) && is_array($this->view->othesFornecimentosPrim) && (count($this->view->othesFornecimentosPrim) > 0)){
			?>
			<div class="row">
				<div class="col">
					<hr/>
					<h5><strong><span>Clientes que visualizaram este item tamberm visualizaram</span></strong></h5>
				</div>
			</div>
			<div class="row" style="margin:auto;" align="center">
				<div class="col-md-1 col-sm-1 col-xs-1" style="margin: auto -15px;" align="left"><button class="btn btn-primary"><<?= isset($this->view->pagCatPri) ?$this->view->pagCatPri ++ : ''?></button></div>
					<div class="col-md-10 col-sm-10  col-xs-10">
						<div class="row">
							<?php 
									for ($i=0, $estoque = $this->view->othesFornecimentosPrim; !($i == count($estoque)); $i++) { 
								
									
							?>
								<div class="col py-2 px-2">
									<a class="link-produto" href="/pedido/produto/detalhes?cd=<?=$estoque[$i]->getProdutoIdProduto();?>">
										<img style="width: 200px; height: 200px;" class="card-img-top a-img-product" src="../files/imagens/<?=$estoque[$i]->getUrl();?>"  alt="<?=$estoque[$i]->getUrl();?>">
									</a>
								</div>
							<?php 
								}
							?>
						</div>
					</div>
				<div class="col-md-1 col-sm-1 col-xs-1" style="margin: auto -15px;" align="right"><button class="btn btn-primary">></button></div>
				<?php 
					}
				?>
			</div>
			<br>
			<br>
			<br>
			<br>
		</div>
	</div>
	<div class="row" style="width: 80%; margin:auto;">
		<div class="col">
			<?php
				
				if(isset($this->view->othesFornecimentosSec) && (is_array($this->view->othesFornecimentosSec)) && (count($this->view->othesFornecimentosSec) > 0)){
			?>
			<div class="row">
				<div class="col">
					<hr/>
					<h5><strong><span>Clientes que compraram este item tamberm compraram</span></strong></h5>
				</div>
			</div>
			<div class="row" style="margin:auto;" align="center">
				<div class="col-md-1 col-ms-1 col-xs-1" style="margin: auto -15px;" align="left"><button class="btn btn-primary"><</button></div>
					<div class="col-md-10 col-sm-10 col-xs-10">
						<div class="row">
							<?php 
									
								for ($i=0, $estoque = $this->view->othesFornecimentosSec; !($i == count($estoque)); $i++) { 
									
							?>
								<div class="col py-2 px-2">
									<a class="link-produto" href="/pedido/produto/detalhes?cd=<?=$estoque[$i]->getProdutoIdProduto();?>">
										<img style="width: 200px; height: 200px;" class="card-img-top a-img-product" src="../files/imagens/<?=$estoque[$i]->getUrl();?>"  alt="<?=$estoque[$i]->getUrl();?>">
									</a>
								</div>
							<?php 
								}
							?>
						</div>
					</div>
				<div class="col-md-1 col-sm-1 col-xs-1" style="margin: auto -15px;" align="right"><button class="btn btn-primary">></button></div>
				<?php 

					}
				?>
			</div>
		</div>
	</div>
	<div class="row mb-3" style="width: 80%; margin:auto;">
		<div class="col"><hr/></div>
	</div>
	<div class="row" style="width: 80%; margin:auto;">
		<div class="col-md-1 col-ms-12">
			<img src="../files/imagens/perfil/avatar.png" style="width: 100px; height: 100px;">
		</div>
		<div class="col-md-11 col-sm-12" align="left">
			<form action="/produto/comentar" style="width: 30%;" id="formComentario">
				<fieldset><legend align="">Deixe seu comentário:</legend>
					<div class="form-group">
						<textarea class="form-control" name="comentario" id="textComentario" rows="3" cols="6"></textarea>
						<input type="hidden" name="produto" value="<?=$this->view->idProduto?>">
					</div>
					<div class="form-group" align="right">
						<button class="btn btn-success"><strong>Comentar</strong></button>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
	<div class="row pb-5" style="width: 80%; margin:auto;">
		<div class="col" align="left" id="comentarios">
			<?php

				if($this->view->usuario != false){

					if($this->view->comentarios != false){

						$idPessoa = $this->view->usuario->getIdPessoa();
				

						for ($i=0, $comentarios = $this->view->comentarios; !($i == count($comentarios) ); $i++) { 
							$dtCom = $this->view->comentarios[$i]->getDtComentario();
							$explDt = explode(' ', $dtCom);
							$hora = $explDt[1];
							$data = array_reverse(explode('-',$explDt[0]));

							$idComentario = $this->view->comentarios[$i]->getIdCometario();
							$idUsuarioComentario = $this->view->comentarios[$i]->getUsuarioIdUsuario();
							
			?>
				<div class="row listComent">
					<div class="col-md-1 col-sm-12">
						<img class="rounded-circle"  style="width: 70px; height: 70px;" src="../files/imagens/perfil/<?=$this->view->comentarios[$i]->getImg();?>" align="imagem do usuario"/>
					</div>
					<div class="col-md-11 col-sm-12" align="left">
						<div class="row">
							<div class="col"><span><strong><?='@'.$comentarios[$i]->getNomePessoa()?></strong><?= ' '.$hora.'  '.$data[0].'-'.$data[1].'-'.$data[2];?> </span>
								<?php
									if($idPessoa == $idUsuarioComentario){
								?>
									<span><a href="/produto/comentario/delete"><sub>Excluir</sub></a></span>
									<span class="ml-2"><a href="/produto/comentario/editar"><sub>Editar</sub></a>
								<?php
									}
								?>
							</div>
						</div>
						<div class="row">
							<div class="col text-dark"><p><?="\t\t".$comentarios[$i]->getTextoComentario()?></p></div>
						</div>
						<div class="row">
							<div class="col">
								<sub><a href="/produto/comentario/curtir?cm=<?=$idComentario?>&cu=<?=$idUsuarioComentario?>">Curtir</a></sub><sub class="ml-2"><a href="/produto/comentario/responder?cm=<?=$idComentario?>&cu=<?=$idUsuarioComentario?>">Responder</a></sub>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col" align="left;">
						<hr style="width: 30%; margin-left: 0;" />
					</div>
				</div>
			<?php
						}
					}else{

			?>
				<div class="row listComent">
					<div class="col">
						Faça um comentário...
					</div>
				</div>
			<?php
				}

			}
			?>
		</div>
	</div>
</div>
