
<div class="container-fluid" id="detalheProduto" style="">
	<div class="row">
		<div class="col-md-5" align="center">
				<img class="img-produto" src="../files/imagens/<?=$this->view->imagensProduto[0]->getUrl();?>" style="width: 75%; height: 75%;" data-zoom-image="../files/imagens/<?=$this->view->imagensProduto[0]->getUrl();?>"><br><br>
			<div id="gali">
			<?php
				for ($i=0, $imagens = $this->view->imagensProduto;!($i == count($imagens)) ; $i++) { 
					# code...
				
			 ?>
			 		<a href="#" data-image="../files/imagens/<?=$imagens[$i]->getUrl();?>" data-zoom-image="../files/imagens/<?=$imagens[$i]->getUrl();?>">
					    <img class="img-produto-opt" src="../files/imagens/<?=$imagens[$i]->getUrl();?>" style="width: 100px; height: 100px;">

					 </a>
			 		
			 	
			 <?php 
			 	}
			 ?>
			 </div>
		</div>
		<div class="col-md-5" align="left">
			<h3>Condiçoes</h3>
			<h4><strong><?=$this->view->produto->getNomeProduto();?></strong></h4>
			<p>Classinficação</p>
			<p><sup>Por: </sup><span id="vlP"><?= number_format($this->view->fornecimento->getVlVenda(), 2, ',','.') ?></span> & frete</p>
			<hr align="left" width="50%;" />
			<h4>Detalhes do produto</h4>
			<p>ASIN:</p>
			<p>Dimensões d produto:</p>
			<p>Número do modelo</p>
			<p>Código de barras:</p>
			<p>Avaliação do clientes:</p>
			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
		</div>
		<div class="col-md-2" align="center">
			<div class="row my-4">
				<div class="col">
					Compartilhe <a href="" class="mx-1"><i class="fab fa-whatsapp fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-twitter fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-instagram fa-1x"></i></a>
								<a href="" class="mx-1"><i class="fab fa-facebook fa-1x"></i></a>
				</div>
			</div>
			<div class="row" style="box-shadow: 1px 1px 2px #000">
				<div class="col">
					<form class="py-4" method="post" action="/pedido/produto/frete" id="formFretQtd">
						<div class="form-group row">
							<div class="col" align="left">
								<label for="qtd"><strong>Quantidade</strong></label>
							</div>
							<div class="col">
								<select class="form-control" id="qtd" name="qtd">
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col">
								<button class="btn btn-warning"><strong>Add. Carrinho</strong></button>
								<button class="btn btn-warning"><strong>Compar Agora</strong></button>
							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="left">
								<p><strong>Sua compra é <a href="#" class="text-success">segura</a></strong></p>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-sm-3" align="left">
								<label for="frete"><strong>Calc. Frete</strong></label>
							</div>
							<div class="col-sm-9">
								<input type="text" placeholder="CEP" name='cep' class="form-control" id="frete"/><br>

							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="center" id="response">
							</div>
						</div>
						<div class="form-group row">
							<div class="col" align="center">
								<button class="btn btn-success" id="calcularFrete"><strong>Calcular</strong></button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<hr/>
			<h5><strong><span>Clientes que visualizaram este item tamberm visualizaram</span></strong></h5>

			<div class="row" style="margin:auto;" align="center">
				<div class="col-md-1" style="margin: auto;" align="left"><button class="btn btn-primary"><</button></div>
					<div class="col-md-10">
						<div class="row">
							<?php 
								for ($i=0, $estoque = $this->view->othesFornecimentosPrim; !($i == count($estoque)); $i++) { 
									
							?>
								<div class="col py-2 px-2">
									<a class="link-produto" href="/pedido/produto/detalhes?cd=<?=$estoque[$i]->getProdutoIdProduto();?>">
										<img style="width: 200px; height: 200px;" class="card-img-top a-img-product" src="../files/imagens/<?=$estoque[$i]->getUrl();?>"  alt="<?=$estoque[$i]->getUrl();?>">
									</a>
								</div>
							<?php 
									
								}
							?>
						</div>
					</div>
				<div class="col-md-1" style="margin: auto;" align="right"><button class="btn btn-primary">></button></div>
			</div>
			<br>
			<br>
			<br>
			<br>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<hr/>
			<h5><strong><span>Clientes que compraram este item tamberm compraram</span></strong></h5>
			<div class="row" style="margin:auto;" align="center">
				<div class="col-md-1" style="margin: auto;" align="left"><button class="btn btn-primary"><</button></div>
					<div class="col-md-10">
						<div class="row">
							<?php 
								for ($i=0, $estoque = $this->view->othesFornecimentosSec; !($i == count($estoque)); $i++) { 
									
							?>
								<div class="col py-2 px-2">
									<a class="link-produto" href="/pedido/produto/detalhes?cd=<?=$estoque[$i]->getProdutoIdProduto();?>">
										<img style="width: 200px; height: 200px;" class="card-img-top a-img-product" src="../files/imagens/<?=$estoque[$i]->getUrl();?>"  alt="<?=$estoque[$i]->getUrl();?>">
									</a>
								</div>
							<?php 
									
								}
							?>
						</div>
					</div>
				<div class="col-md-1" style="margin: auto;" align="right"><button class="btn btn-primary">></button></div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<hr/>
			<h5 class=""><strong><span>Perguntas e respostas do cliente</span></strong></h5>
			<div class="form-group">
				<input type="text" name="searchResponse" class="form-control" placeholder="Faça uma pergunta e encontre uma resposta.">
			</div>
			<br>
			<br>
			<br>
			<br>
		</div>
	</div>
</div>
