<div class="row" style="">
	<div class="col-md-12"  style="padding: 20px 40px;">
		<form method="post" class="was-validated" action="/produto/atualizar" enctype="multipart/form-data" id="editarProduto">
			<input type="hidden" name="prod" value="<?=$this->view->result->getIdProduto();?>">
			<fieldset class=""><legend><strong>Editar produto</strong></legend>
				<div class="row">
					<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<label for="idNomeProduto">Nome</label>
									<input value="<?= $this->view->result->getNomeProduto(); ?>" type="text" name="nome" id="idNomeProduto" class="form-control" placeholder="Nome do produto" required="required">
								</div>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
								<div class="form-group">
									<div class="form-group">
										<label for="idMarc">Marca: </label>
										<select class="form-control " id="idMarc" name="marca" required="required">
											<?php 
											for ($i=0; !($i == count($this->view->marcas)); $i++) { 

											$selected = "";

											if($this->view->result->getMarca()->getIdMarca() == $this->view->marcas[$i]->getIdMarca()){

												$selected = "selected=\"selected\"";
											}
										?>
											<option <?=$selected?>  value="<?=$this->view->marcas[$i]->getIdMarca()?>" ><?= $this->view->marcas[$i]->getNomeMarca()?></option>
										<?php 
											}
										?>
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<?php
								for ($i=0; !($i == count($this->view->img)) ; $i++) { 
									$col = 12/count($this->view->img);
								
							 ?>
								<div class="col-xs-<?=$col?> col-sm-<?=$col?> col-md-<?=$col?> col-lg-<?=$col?>">
									<div class="form-group">
										<div class="form-group">
											<label for="upload-<?=$i+1?>">Imgem do produto nº <?=$i+1?>: </label>
											<input type="file" class="form-control upload" id="upload-<?=$i+1?>" name="imgProduto-<?=$i+1?>" required="required">
										</div>
									</div>
								</div>
							<?php

								}
							 ?>
						</div>

						<?php
							$primaria = [];
							$secundaria = [];

							$prodCateg = $this->view->result->getProdCateg();
							if($prodCateg){
								for ($i=0; !($i == count($prodCateg)) ; $i++) { 

									$categoria = $prodCateg[$i]->categoria();

									if(($prodCateg[$i]->getClassificCateg() == 'primaria') && ($categoria != false)){

										$primaria['categ']=$categoria[0]->getNomeCategoria();
										$primaria['id']= $categoria[0]->getIdCategoria();

									}elseif(($prodCateg[$i]->getClassificCateg() == 'secundaria') && ($categoria != false)){

										$secundaria['categ']=$categoria[0]->getNomeCategoria();
										$secundaria['id']= $categoria[0]->getIdCategoria();
									}
								}
							}
						?>
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idCategoria">Categoria: </label>
									<input type="text" name="" id="idCategoria" class="form-control" required="required" value="<?=$primaria['categ'] ?? ''?>">
									<input type="hidden" name="categoria" value="<?=$primaria['id'] ?? ''?>">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idSubCategoria">Subcategoria: </label>
									<input type="text" name="" id="idSubCategoria" class="form-control" required="required" value="<?=$secundaria['categ'] ?? ''?>">
									<input type="hidden" name="subCategoria" value="<?=$secundaria['id'] ?? ''?>">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idPeso">Peso Kg: </label>
									<input type="text" name="peso" id="idPeso" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idLargura">Largura: </label>
									<input type="text" name="largura" id="idLargura" class="form-control" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idAtura">Atura: </label>
									<input type="text" name="altura" id="idAtura" class="form-control" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idUniMed">Unidade Medida: </label>
									<input type="text" name="uniMed" id="idUniMed" class="form-control" required="required">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idExtMin">Estoque mínimo:</label>
									<input class="form-control" name="extMin" rows="2" id="idExtMin" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idCor">Cor:</label>
									<input class="form-control" name="cor" rows="2" id="idCor" required="required">
								</div>
							</div>
							<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
								<div class="form-group">
									<label for="idTexto">Texto promorcional:</label>
									<textarea class="form-control" name="texto" rows="2" id="idTexto" required="required"></textarea>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="form-group form-check">
									<label class="form-check-label" for="idSobrescrever" style="margin-right: 25px;">Sobrescrever imagem no destino?</label>
									<input class="form-check-input" type="checkbox" name="sobrescrever" id="idSobrescrever"></input>
								</div>
							</div>
						</div>
					</div>	
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="containerImg">
						<div class="row">
							<?php
							if(isset($this->view->imgProduto) && (count($this->view->imgProduto) > 0)){
								for ($i=0; !($i == count($this->view->imgProduto)); $i++) { 
									
							?>
							<img src="../../files/imagens/<?=$this->view->imgProduto[$i]->getUrl();?>" style="width: 160px;" class="mb-2" id="img-<?=$i+1?>">
							<?php
							
									
									}
								}

							?>
						</div>
						<div class="row">
						<?php
								for ($i=0; !($i == count($this->view->img)) ; $i++) { 
									$col = 12/count($this->view->img);
								
							 ?>
							 <div class="col-12">
								<img class="preview" id="img-<?=$i+1?>" name="imgProduto-<?=$i+1?>"/>
								<?php
									if($i==0){
										echo'<p>Imagem nº1</p>';
									}elseif($i==1){
										echo'<p>Imagem nº2</p>';
									}elseif($i==2){
										echo'<p>Imagem nº3</p>';
									}elseif($i==3){
										echo'<p>Imagem nº4</p>';
									}
								?>
							</div>	
							<?php

								}
							 ?>
						</div>
					</div>	
				</div>
				<button type="submit" class="btn btn-primary">Atualisar</button>  <a href="/produto/all" class="btn link ml-2 btn-danger">Cancelar</a> 
			</fieldset>

		</form>
	</div>
</div>