<div class="row mt-5" id="produtos-relacionados">
	<div class="col-md-12 mt-5" >
		<div class="container-fluid">
			<div class="row mt-5">
				<div class="col-ms-2 col-md-2" style="border-right: solid 1px #ccc;" id="div-form-filtro-relacionados">
				<p><strong>Preço</strong></p>
				<?php
					$preco = 50;
					for ($j=0; !($j == 5) ; $j++) { 
				?>
					<p><input type="radio" name="preco" id="preco-<?=$j?>" class="mr-2">Até R$ <?=$preco?></p>
				<?php
					$preco*=3;

					}
				?>
				<p><strong>Marca</strong></p>
				<?php
					if((isset($this->view->marcas)) && (count($this->view->marcas)) > 0){
						for ($j=0; !($j == count($this->view->marcas)) ; $j++) { 
				?>
					<p><input type="checkbox" name="marca-<?=$this->view->marcas[$j]->getIdMarca();?>" class="mr-2"><?=$this->view->marcas[$j]->getNomeMarca();?></p>
				<?php
						}

					}
				?>
				<p style="margin-bottom: -38px;"><strong>Ranking</strong></p>
				<?php
					$widtStar = 20;
					for ($j=0; !($j == 5) ; $j++) { 
						
				?>
				<p style="margin-bottom: 38px;">
					<div class="row">
						<div class="col">
			 				<div id="barra-detalhes" class="row">
				 				<span class="bg-detalhes" style="width: <?=$widtStar.'%;'?>"></span>
					 			<div class=" estrelas-detalhes">
					 				<?php for ($i=0; !($i == 5); $i++):?>
					 					<span class="star-detalhes" id="<?=$i?>">
					 						<span class="starAbsolute-detalhes"></span>
					 					</span>
					 				<?php endfor;?>
					 			</div>
					 		</div>
				 		</div>
			 		</div>
				</p>
				<?php
					$widtStar += 20;
					}
				?>
				<p>
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
				</p>
				</div>
				<div class="col-sm-10 col-md-10">
					<div class="row" id="divProdRelac">
						<?php
							if(isset($this->view->result) && (count($this->view->result) > 0)){
								for ($i=0; !($i == count($this->view->result)) ; $i++) { 
									

						?>
						<div class="col-sm-2 col-xs-2 col-md-3 mb-3">
							<div class="card" style="">
						  		<div class="card-body">
								  	<div class="row">
								  		<div class="col">
											<h5 style="color:#9400D3; text-align: center;"><?=$this->view->result[$i]->getProdutoNome();?>
											</h5>
										</div>
									</div>
									<div class="row mt-3">
										<div class="col" style=" align-items: center; text-align: center">
											<img style="width: 200px; height: 200px;" class="" src="../files/imagens/<?=$this->view->result[$i]->getUrl()?>"  alt="<?=$this->view->result[$i]->getUrl();?>">
												
										</div>
									</div>
									<div class="row my-2">
										<div class="col" align="center">
											<?=$this->view->result[0]->getTexto();?>
										</div>
									</div>
									<div class="row my-1">
										<div class="col" align="center">
											<span class="h4">
												<?php 
													$preco = number_format($this->view->result[$i]->getVlVenda(), 2, ',', '.');
													$preco = explode(',', $preco);
												?>
												<sup><small>R$</small></sup> <?=$preco[0]?><sup><small><?=$preco[1]?></small></sup>
											</span>
											
										</div>
									</div>
									<div class="row mt-1">
										<div class="col" align="center">
											 <a class="btn text-light link-produto" href="/pedido/produto/detalhes?cd=<?=$this->view->result[$i]->getProdutoIdProduto();?>">Add. carrinho</a>
										</div>
									</div>
						  		</div>
							</div>
						</div>
						<?php
							# code...
								}
							}
						?>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>