
<div class="container-fluid" id="relacionados">
	<div class="row">
		<div class="col-xs-2 col-md-2">
			<form method="post" action="/produto/filtro">
				<div class="row opcoes-pesquisa">
					
					<div class="col">
						<?php 
							foreach ($this->view->optionsLeft as $key => $value)
							{
						?>	
							<div class="row">
								<div style="display: flex;flex-direction: column;"><strong><?=$key;?></strong>
									<?php for ($i=0; !($i == count($value)) ; $i++) { 

										$typeInput = 'checkbox';
										$keyProduto = 'Categoria';

										switch ($key) {
											case 'Preco':
												$typeInput = 'radio';
												$keyProduto = 'Preco';
												break;

											case 'Condições':
												$typeInput = 'radio';

												$keyProduto = 'Condicoes';
												break;

											case 'Mais procurados':
												$keyProduto = 'Procurados';
												break;
										}
									?>
										<label>
											<input type="<?=$typeInput;?>" name="produtos[<?=$keyProduto?>][]" value="<?= $value[$i];?>">
											<?=$value[$i];?>
										</label>

									<?php }

									?>
								</div>
							</div>
							<hr width="50%" align="center" style="background-color: #8B008B">
						<?php 
							}
						?>
					</div>
					<div class="col">
						<div class="form-group">
							<!-- input para teste
							<button type="submit" class="btn btn-success">Enviar</button>-->
							<button type="button" class="btn btn-success" id="filtroLateral" data-toggle="modal" data-target="#myModal"><i class="fas fa-search fa-2x"></i></button>
						</div>
					</div>

				</div>
			</form>
		</div>
		<div class="col-xs-10 col-md-10" id="itens">
		<div class="row">
		<?php for ($i = 0, $fornecimento =$this->view->fornecimento; !($i == count($fornecimento)); $i++){
			$valueVenda = number_format($fornecimento[$i]->getVlVenda(), 2, ',', '.');
			$valueVenda = explode(',', $valueVenda);

		 ?> 
			    <div class="col-xs-6 col-md-2 card-produto">
			    	<div class="card produto-item">
			    		<a class="produto-item link-produto" href=<?= "/estoque/detalhes?cd=".$fornecimento[$i]->getProdutoIdProduto();?> >
			    		<div align="center" style="padding-top: 10px">
			    			<img src="../files/imagens/xbox_controller.jpeg" class="produto" style="width: 100px; height: 100px;">
			    		</div>
				    	<div class="card-body">
				    		<div>
				    			<h3><?= $fornecimento[$i]->getProdutoNome();?></h3>
					        	<p><?= $fornecimento[$i]->getTexto();?></p>
					        	<p>
					        		<strong><sup><small>R$</small></sup><?=$valueVenda[0]?><sup><small><?= $valueVenda[1]?></small></sup></strong>
					        	</p>
				    		</div>
				    	</div>
				    	</a>
				    	<div class="card-footer">
				    		<div class="child-card-footer">
				    			<button type="button" class="btn btn-primary  button-modal" data-toggle="modal" data-target="#myModal">
								  Mais detalhes
								</button>
					        	<ul class="curt-lista">
					        		<li class="">
					        			<button class="btn btn-xs btn-default" style='font-size:20px;'>&#128077;</button>
					        			<span>1</span>
					        		</li>
					        		<li class="">
					        			<button class="btn btn-xs btn-default" style='font-size:20px;'>&#128078;</button>
					        			<span>1</span>
					        		</li>
					        	</ul>
				        	</div>
					    </div>
				    </div>
			    </div>
	    
  	<?php } ?>
  	</div><hr style="border: none;">

		<div class="row">
			<div class="col-md-12">
				<nav aria-label="Page navigation example" id="pagination">
				  <ul class="pagination justify-content-end">
				  	<?php 
				  		$previous = $this->view->pagina - 1;
				  		$blockPrevius = ($this->view->pagina  == 1) ? 'disabled' : '';
				  	?>
				    <li class="page-item <?= $blockPrevius ?>">
				      <a class="page-link" href="/produto/show?pagina=<?=$previous?>" tabindex="-1"><strong>Previous</strong></a>
				    </li>

				    <?php
				    	for ($i=0; !($i == $this->view->totPaginas); $i++) {

				    		$estilo = ($this->view->pagina == ($i + 1)) ? 'active' : '';
				    		
				    ?>
						<li class="page-item <?= $estilo ?>">
							<a class="page-link" href="/produto/show?pagina=<?= $i+1?>">
							<?= $i+1?>
							</a>
						</li>
				    <?php 
						}

						$blockNext = ($this->view->pagina  == $this->view->totPaginas) ? 'disabled' : '';
						$next = $this->view->pagina + 1;
				    ?>

				    <li class="page-item <?= $blockNext;?>">
				      <a class="page-link" href="/produto/show?pagina=<?= $next?>"><strong>Next</strong></a>
				    </li>
				  </ul>
				</nav>
			</div>
		</div>
	</div>
		
	</div>
	
</div>