<!--<div class="container">

	<div id="demo" class="carousel slide" data-ride="carousel">
		<ul class="carousel-indicators">
		    <li data-target="#demo" data-slide-to="0" class="active"></li>
		    <li data-target="#demo" data-slide-to="1"></li>
		    <li data-target="#demo" data-slide-to="2"></li>
		</ul>
		<div class="carousel-inner">
		    <div class="carousel-item active">
		      	<img src="files/imagens/images.png" style="width: 80%;height: 50%;"/>
		    </div>
		    <div class="carousel-item">
		      	<img src="files/imagens/xbox_controller.jpeg" style="width: 100%; height: 50%;"/>
		    </div>
		    <div class="carousel-item">
		      	<img src="files/imagens/xbox_controller.jpeg" style="width: 100%;height: 80%;"/>
		    </div>
		</div>
		<a class="carousel-control-prev" href="#demo" data-slide="prev">
		    <span class="carousel-control-prev-icon"></span>
		</a>
		<a class="carousel-control-next" href="#demo" data-slide="next">
		    <span class="carousel-control-next-icon"></span>
		</a>
	</div>
</div><br>-->
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2 col-md-2">
			<div class="container" id="opcoes-pesquisa">
				<div class="row">
					<p>Departamento</p>
				</div>
				<div class="row">
					Avaliação dos clientes
				</div>
				<div class="row">
					<p>Marca</p>
				</div>
				<div class="row">
					<p>Preço</p>
				</div>
				<div class="row">
					<p>Condição</p>
				</div>
			</div>
		</div>
		<div class="col-xs-10 col-md-10">
	<?php for ($i = 0, $produtos =$this->view->produtos; !($i == count($produtos)); $i++){ ?>
		<div class="row">
			<?php 
				for ($j=0; !($j == count($produtos[$i])); $j++) { 
					
			?>
			    <div class="col-xs-6 col-md-2" id="card">
			    	<div class="card produto-item">
			    		<a class="produto-item" href=<?= "/produto/detals?cd=".$produtos[$i][$j]->getIdProduto();?> >
			    		<div align="center" style="padding-top: 10px">
			    			<img src="../files/imagens/xbox_controller.jpeg" class="produto" style="width: 100px; height: 100px;">
			    		</div>
				    	<div class="card-body">
				    		<div>
				    			<h3><?= $produtos[$i][$j]->getNomeProduto();?></h3>
					        	<p><?= $produtos[$i][$j]->getTextoPromorcional();?></p>
					        	<p>
					        		<strong><sup><small>R$</small></sup><?= $produtos[$i][$j]->getPreco();?><sup><small>00</small></sup></strong>
					        	</p>
				    		</div>
				    	</div>
				    	</a>
				    	<div class="card-footer">
				    		<div class="child-card-footer">
				    			<button type="button" class="btn btn-primary  button-modal" data-toggle="modal" data-target="#myModal">
								  Mais detalhes
								</button>
					        	<ul class="curt-lista">
					        		<li class="">
					        			<button class="btn btn-xs btn-default" style='font-size:20px;'>&#128077;</button>
					        			<span>1</span>
					        		</li>
					        		<li class="">
					        			<button class="btn btn-xs btn-default" style='font-size:20px;'>&#128078;</button>
					        			<span>1</span>
					        		</li>
					        	</ul>
				        	</div>
					    </div>
				    </div>
			    </div>

		    <?php
				}
		     ?>
	    </div><hr style="border: none;">
  	<?php } ?>
		</div>
	</div>
	
</div>