<div class="container-fluid standard-background">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="/produto/cadastrar" class="btn button-modal mb-2">
					<i class="fas fa-plus-circle fa-2x"></i>
				</a>
				 <table class="table table-hover">
				    <thead>
				      <tr>
				        <th>Nome</th>
				        <th>Estoque</th>
				        <th>Preço</th>
				        <th>Ação</th>
				      </tr>
				    </thead>
				    <tbody>
				    	<?php 
							for ($i=0; !($i == count($this->view->tableProdutos)); $i++) { 
								# code...
							
						?>
							<tr>
								<td><?=$this->view->tableProdutos [$i]->getNomeProduto();?></td>
								<td><?=$this->view->tableProdutos [$i]->getEstoque();?></td>
								<td><?=$this->view->tableProdutos [$i]->getPreco();?></td>
								<td>
									<a href="/produto/editar?id=<?=$this->view->tableProdutos [$i]->getIdProduto() ?>" class="btn button-modal mr-2">
										<i class="fas fa-pencil-alt"></i>
									</a>
									<a href="/produto/visualizar?id=<?= $this->view->tableProdutos [$i]->getIdProduto() ?>" class="btn btn-primary mr-2">
										<i class="fas fa-search-plus"></i>
									</a>
									<a href="/produto/excluir?id=<?= $this->view->tableProdutos [$i]->getIdProduto() ?>" class="btn btn-danger">
										<i class="fas fa-trash-alt"></i>
									</a>
								</td>
							</tr>

						<?php 
							}
						?>
				    </tbody>
				  </table>
			</div>
		</div>
	</div>
</div>
