<form action="/action_page.php" class="was-validated" id="cadastro">
    <div class="opcao_pessoa">
      <label for="id_cpf">CPF:</label>
      <input type="radio" class="" id="id_cpf"  name="documento" checked>
      <label for="id_cnpj">CNPJ:</label>
      <input type="radio" class="" id="id_cnpj"  name="documento">
    </div>
    <div class="form-group cpf">
      <label for="uname">Nome:</label>
      <input type="text" class="form-control" id="uname" placeholder="Enter username" name="uname" required>
    </div>
    <div class="form-group cpf">
      <label for="pwd">CPF:</label>
      <input type="text" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
    </div>
    <div class="form-group form-check cpf">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
      </label>
    </div>

    <!--  CNPJ -->
    <div class="form-group cnpj">
      <label for="uname">Razão Social:</label>
      <input type="text" class="form-control" id="uname" placeholder="Enter username" name="uname" required>
    </div>
    <div class="form-group cnpj">
      <label for="pwd">CNPJ:</label>
      <input type="text" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>