<form action="/action_page.php" class="was-validated" id="cadastro">
  <div class="opcao_pessoa">
    <label for="id_cpf">CPF:</label>
    <input type="radio" class="" id="id_cpf"  name="documento" checked>
    <label for="id_cnpj">CNPJ:</label>
    <input type="radio" class="" id="id_cnpj"  name="documento">
  </div>
  <div class="linha cpf">
    <fieldset><legend>Dados pessoais</legend>
      <div class="coluna">
        <div class="form-group cpf">
          <label for="id_nome">Nome:</label>
          <input type="text" class="form-control" id="id_nome" placeholder="Enter username" name="nome" required>
        </div>
        <div class="form-group cpf">
          <label for="id_sobrenome">Sobrenome:</label>
          <input type="text" class="form-control" id="id_sobrenome" placeholder="Enter username" name="sobrenome" required>
        </div>
        <div class="form-group cpf">
          <label for="id_nascimento">Data Nascimento:</label>
          <input type="date"  max= <?php echo date('Y-m-d'); ?> class="form-control" id="id_nascimento"  name="dt_nascimento" required>
        </div>
        <div class="form-group cpf">
          <label for="pwd">CPF:</label>
          <input type="text" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
        </div>
      </div>
    </fieldset>
    <fieldset><legend>Contato</legend>
      <div class="coluna">
        <div class="form-group cpf">
          <label for="id_email">Email:</label>
          <input type="email" class="form-control" id="id_email" placeholder="nome@gmail.com"  name="email" required>
        </div>
        <div class="form-group cpf">
          <label for="id_telefone">Telefone:</label>
          <input tyte="tel" class="form-control" id="id_telefone" placeholder="(00)0000-0000"  name="telefone">
        </div>
        <div class="form-group cpf">
          <label for="id_celular">Celular:</label>
          <input tyte="tel" class="form-control" id="id_celular" placeholder="(00)00000-0000" name="celular" required>
        </div>
        <div class="form-group form-check cpf">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
          </label>
        </div>
      </div>
    </fieldset>
    <fieldset><legend>Endereco</legend>
      <div class="coluna">
        <div class="form-group cpf">
          <label for="id_uf">UF:</label>
          <select name="uf" class="form-control" id="id_uf">
            <option value="ma">MA</option>
            <option value="sp">SP</option>
            <option value="rj">RJ</option>
          </select>
        </div>
        <div class="form-group cpf">
          <label for="id_uf">Cidade:</label>
          <select name="uf" class="form-control" id="id_uf">
            <option value="sao luis">São Luis</option>
            <option value="sao paulo">São Paulo</option>
            <option value="rio de janeiro">Rio de Janeiro</option>
          </select>
        </div>
        <div class="form-group cpf">
          <label for="id_logradouro">Logradouro:</label>
          <input type="text" class="form-control" name="logaradouro" id="id_logradouro">
        </div>
        
      </div>
    </fieldset>
  </div>
    
    <!--  CNPJ -->
   

  <div class="linha cnpj">
    <fieldset><legend>Dados pessoais</legend>
      <div class="coluna">
        <div class="form-group cnpj">
          <label for="id_nome">Nome:</label>
          <input type="text" class="form-control" id="id_nome" placeholder="Enter username" name="nome" required>
        </div>
        <div class="form-group cnpj">
          <label for="id_sobrenome">Sobrenome:</label>
          <input type="text" class="form-control" id="id_sobrenome" placeholder="Enter username" name="sobrenome" required>
        </div>
        <div class="form-group cnpj">
          <label for="id_cnpj">CNPJ:</label>
          <input type="text" class="form-control" id="id_cnpj" placeholder="Enter password" name="cnpj" required>
        </div>
      </div>
    </fieldset>
    <fieldset><legend>Contato</legend>
      <div class="coluna">
        <div class="form-group cnpj">
          <label for="id_email">Email:</label>
          <input type="email" class="form-control" id="id_email" placeholder="nome@gmail.com"  name="email" required>
        </div>
        <div class="form-group cnpj">
          <label for="id_telefone">Telefone:</label>
          <input tyte="tel" class="form-control" id="id_telefone" placeholder="(00)0000-0000"  name="telefone">
        </div>
        <div class="form-group cnpj">
          <label for="id_celular">Celular:</label>
          <input tyte="tel" class="form-control" id="id_celular" placeholder="(00)00000-0000" name="celular" required>
        </div>
        <div class="form-group form-check cnpj">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
          </label>
        </div>
      </div>
    </fieldset>
    <fieldset><legend>Endereco</legend>
      <div class="coluna">
        <div class="form-group cnpj">
          <label for="id_uf">UF:</label>
          <select name="uf" class="form-control" id="id_uf">
            <option value="ma">MA</option>
            <option value="sp">SP</option>
            <option value="rj">RJ</option>
          </select>
        </div>
        <div class="form-group cnpj">
          <label for="id_uf">Cidade:</label>
          <select name="uf" class="form-control" id="id_uf">
            <option value="sao luis">São Luis</option>
            <option value="sao paulo">São Paulo</option>
            <option value="rio de janeiro">Rio de Janeiro</option>
          </select>
        </div>
        <div class="form-group cnpj">
          <label for="id_logradouro">Logradouro:</label>
          <input type="text" class="form-control" name="logaradouro" id="id_logradouro">
        </div>
        
      </div>
    </fieldset>
  </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>