<form action="/action_page.php" class="was-validated" id="cadastro">
  <div class="opcao_pessoa">
    <label for="id_cpf">CPF:</label>
    <input type="radio" class="" id="id_cpf"  name="documento" checked>
    <label for="id_cnpj">CNPJ:</label>
    <input type="radio" class="" id="id_cnpj"  name="documento">
  </div>
  <div class="linha">
    <div class="coluna">
      <div class="form-group cpf">
        <label for="id_nome">Nome:</label>
        <input type="text" class="form-control" id="id_nome" placeholder="Enter username" name="nome" required>
      </div>
      <div class="form-group cpf">
        <label for="id_sobrenome">Sobrenome:</label>
        <input type="text" class="form-control" id="id_sobrenome" placeholder="Enter username" name="sobrenome" required>
      </div>
      <div class="form-group cpf">
        <label for="id_nascimento">Data Nascimento:</label>
        <input type="date" max="<?php echo date('now'); ?>" class="form-control" id="id_nascimento"  name="dt_nascimento" required>
      </div>
    </div>
    <div class="coluna">
      <div class="form-group cpf">
        <label for="pwd">CPF:</label>
        <input type="text" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
      </div>
      <div class="form-group cpf">
        <label for="id_uf">UF:</label>
        <select name="uf" class="form-control" id="id_uf">
          <option value="ma">MA</option>
          <option value="sp">SP</option>
          <option value="rj">RJ</option>
        </select>
      </div>
      <div class="form-group cpf">
        <label for="id_uf">Cidade:</label>
        <select name="uf" class="form-control" id="id_uf">
          <option value="sao luis">São Luis</option>
          <option value="sao paulo">São Paulo</option>
          <option value="rio de janeiro">Rio de Janeiro</option>
        </select>
      </div>
      <div class="form-group form-check cpf">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
        </label>
      </div>
    </div>
  </div>
    
    <!--  CNPJ -->
    <div class="form-group cnpj">
      <label for="uname">Razão Social:</label>
      <input type="text" class="form-control" id="uname" placeholder="Enter username" name="uname" required>
    </div>
    <div class="form-group cnpj">
      <label for="pwd">CNPJ:</label>
      <input type="text" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>