<form method="post" action="/login/submit" id="login" class="needs-validation" novalidate>
    <div class="form-group bem-vindo">
      <span style="font-size: 48px; color: #8B008B;">
       <i class="far fa-user fa-5x"></i>
      </span>
    </div>
    <div class="form-group bem-vindo">Bem-Vindo</div>
    <hr/>
    <div class="form-group">
        <label for="id_email">Email</label>
        <input type="email" name="email" id="id_email" class="form-control" placeholder="exemplo@gmail.com" required>
        <!--
        <div class="valid-feedback">Valido.</div>
        <div class="invalid-feedback">Por favor, preencha este campo.</div>
        -->
    </div>
    <div class="form-group">
        <label for="id_password">Senha</label>
        <input type="password" name="senha" id="id_password" class="form-control" required>
        <!--
        <div class="valid-feedback">Valido.</div>
        <div class="invalid-feedback">Por favor, preencha este campo.</div>
        -->
    </div>
    <div class="form-group form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="manter"> Manter-me conectado.
      </label>
    </div>
    <div class="form-group rodape">
        <button type="submit" class="btn btn-primary">Entrar</button>
        <a href="/home/cadastro" class="link">Inda não sou cadastrado(a)</a>
    </div>
</form>