

<div class="col-sm-12">
	<div class="row">
		<div class="col" align="left">
			 <?php
			 	$tipo = 'Pedidos';
			 	if(isset($this->view->tipo) && ($this->view->tipo == 'prevenda')){
			 		$tipo = 'Prevendas';
			 	}elseif(isset($this->view->tipo) && ($this->view->tipo == 'orcamento')){
			 		$tipo = 'Orçamentos';
			 	}
			 ?>

			 <?php

			 ?>
			<h3 class="text-dark"><strong><?=$tipo?>: </strong><?=$this->view->pessoa->getNomePessoa();?></h3>
		</div>
	</div>
	<div class="row " align="center">
		<div class="col-sm-6 col-md-6">
			<div class="row">
				<div class="form-group col-sm-5">
					<select class="form-control form-control-sm" name="status" id="pedido-status">
						
						<option value="0" <?= ($this->view->filtro == 0) ? 'selected' : '';?>>Todos</option>
						<option value="1" <?= ($this->view->filtro == 1) ? 'selected' : '';?>>Cancelado</option>
						<option value="2" <?= ($this->view->filtro == 2) ? 'selected' : '';?>>Em andamento</option>
						<option value="3" <?= ($this->view->filtro == 3) ? 'selected' : '';?>>Entregue</option>
					</select>
				</div>
				<div class="col">
					<form method="post" action="/pessoa/compras" class="row" id="form-find-pedido-id">
						<div class="form-group col">
							<input type="text" name="pedido" class="form-control form-control-sm" placeholder="nº pedido" value="<?= (isset($this->view->pedido) && (! empty($this->view->pedido))) ? $this->view->pedido: '' ?>">
						</div>
						<div class="form-group col-sm-2">
							<button class="btn btn-sm btn-success ml-1" type="submit" style="background-color: #9400D3">Buscar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-6" align="right">
			<a href="#" class="btn btn-sm btn-primary">Monitorar pedido</a>
		</div>
	</div>
	<?php

		 if((isset($this->view->pedidos)) && (is_array($this->view->pedidos))){

	?>
	<div class="row">
		<div class="col" align="center">
			<table class="table table-responsive table-light table-hover" id="tbl-itens-cliente">
				<thead>
					<tr>
						<th>Nº</th>
						<th>Data</th>
						<th>Vendedor</th>
						<th>VL. Frete</th>
						<th>NF</th>
						<th>Tot. Desconto</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<?php
						for ($i=0; !($i == count($this->view->pedidos)) ; $i++) { 
							
					?>
						<tr class="pedido-cliente" data-toggle="modal" data-target="#myModal">
							<td><?=$this->view->pedidos[$i]->idPedido;?></td>
							<td><?=$this->view->pedidos[$i]->dtPedido;?></td>
							<td><?=$this->view->pedidos[$i]->vendedor;?></td>
							<td><?=number_format($this->view->pedidos[$i]->frete, 2, ',', '.');?></td>
							<td>-</td>
							<td><?=number_format($this->view->pedidos[$i]->totalDesconto, 2, ',', '.');?></td>
							<td><?=number_format($this->view->pedidos[$i]->total, 2, ',', '.');?></td>
						</tr>

					<?php

						}
					?>
				</tbody>
			</table>
			
		</div>
	</div>
	<div class="row">
		<div class="col">
			<nav aria-label="Page navigation example" id="pagination-compras">
			  <ul class="pagination justify-content-end">
			  	<?php 
			  		$previous = $this->view->pagina - 1;
			  		$blockPrevius = ($this->view->pagina  == 1) ? 'disabled' : '';
			  	?>
			    <li class="page-item <?= $blockPrevius ?>">
			      <a class="page-link" href="/pessoa/compras?pagina=<?=$previous?>&filtro=<?= $this->view->filtro?>" tabindex="-1"><strong>Previous</strong></a>
			    </li>

			    <?php
			    	for ($i=0; !($i == $this->view->totPaginas); $i++) {

			    		$estilo = ($this->view->pagina == ($i + 1)) ? 'active' : '';
			    		
			    ?>
					<li class="page-item <?= $estilo ?>">
						<a class="page-link" href="/pessoa/compras?pagina=<?= $i+1?>&filtro=<?= $this->view->filtro?>">
						<?= $i+1?>
						</a>
					</li>
			    <?php 
					}

					$blockNext = ($this->view->pagina  == $this->view->totPaginas) ? 'disabled' : '';
					$next = $this->view->pagina + 1;
			    ?>

			    <li class="page-item <?= $blockNext;?>">
			      <a class="page-link" href="/pessoa/compras?pagina=<?= $next?>&filtro=<?= $this->view->filtro?>"><strong>Next</strong></a>
			    </li>
			  </ul>
			</nav>
		</div>
	</div>
	<?php

		}else{

	?>	
		<h2 class="alert alert-warning" align="center">Nenhum registro encontrado!</h2>

	<?php	

		}
	?>
</div>