

<div class="col-sm-12">
	<?php

		 if((isset($this->view->pedidos)) && (is_array($this->view->pedidos))){

	?>
	<div class="row">
		<div class="col" align="left">
			 <?php
			 	$tipo = 'Pedidos';
			 	if(isset($this->view->tipo) && ($this->view->tipo == 'prevenda')){
			 		$tipo = 'Prevendas';
			 	}elseif(isset($this->view->tipo) && ($this->view->tipo == 'orcamento')){
			 		$tipo = 'Orçamentos';
			 	}
			 ?>

			 <?php

			 ?>
			<h3 class="text-dark"><strong><?=$tipo?>: </strong><?=$this->view->pessoa->getNomePessoa();?></h3>
		</div>
	</div>
	<div class="row " align="center">
		<div class="col-sm-6 col-md-6">
			<form method="post" action="#" class="row">
				<div class="form-group col-sm-5">
					<select class="form-control form-control-sm" name="status">
						<option>Todos</option>
						<option>Cancelado</option>
						<option>Em aberto</option>
					</select>
				</div>
				<div class="form-group col-sm-5">
					<input type="text" name="pedido" class="form-control form-control-sm" placeholder="nº pedido">
				</div>
				<div class="form-group col-sm-2">
					<button class="btn btn-sm btn-success ml-1" type="button" style="background-color: #9400D3">Buscar</button>
				</div>
			</form>
		</div>
		<div class="col-sm-6 col-md-6" align="right">
			<a href="#" class="btn btn-sm btn-primary">Monitorar pedido</a>
		</div>
	</div>
	<div class="row">
		<div class="col" align="center">
			<table class="table table-light table-hover" id="tbl-itens-cliente">
				<thead>
					<tr>
						<th>Nº</th>
						<th>Data</th>
						<th>Vendedor</th>
						<th>VL. Frete</th>
						<th>NF</th>
						<th>Tot. Desconto</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<?php
						for ($i=0; !($i == count($this->view->pedidos)) ; $i++) { 
							
					?>
						<tr class="pedido-cliente" data-toggle="modal" data-target="#myModal">
							<td><?=$this->view->pedidos[$i]->idPedido;?></td>
							<td><?=$this->view->pedidos[$i]->dtPedido;?></td>
							<td><?=$this->view->pedidos[$i]->vendedor;?></td>
							<td><?=number_format($this->view->pedidos[$i]->frete, 2, ',', '.');?></td>
							<td>-</td>
							<td><?=number_format($this->view->pedidos[$i]->totalDesconto, 2, ',', '.');?></td>
							<td><?=number_format($this->view->pedidos[$i]->total, 2, ',', '.');?></td>
						</tr>

					<?php

						}
					?>
				</tbody>
			</table>
			
		</div>
	</div>
	<?php

		}else{

	?>
		<h2 class="alert alert-warning" align="center">Nenhum registro encontrado!</h2>

	<?php	

		}
	?>
</div>