<div class="row">
	<div class="col">
		<div class="row">
			<div class="col CartaoCredito"></div>
			<div class="col Boleto"></div>
			<div class="col Debito"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col">
		<form>
			<div class="form-group">
				<input type="text" name="NumeroCartao" id="NumeroCartao">
			</div>
			<div class="form-group" id="BandeiraCartao">
				
			</div>
		</form>
	</div>
</div>