<div class="row" style="background-color: #fff; width: 100%;  margin: auto;" align="left">
	<div class="col py-3">
		<div class="row mb-2"><div class="col" id="msg-logradouro"></div></div>
		<div class="row mb-4" id="titulo-logradouro">
			<div class="col h4" style="width: 80%;" align="center"><strong>Cadastrar Endereço</strong></div>
		</div>
		<div class="row mb-4" id="msg-cep" style="display: none;" align="center">
			<div class="col alert alert-warning" style="width: 80%;" align="center"><strong></strong></div>
		</div>
		<div class="row">
			<form method="post" id="cadastro-logradouro" action="/logradouro/salvar" enctype="multipart/form-data" style="margin: auto; width: 80%;">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="cep">Cep</label>
							<input type="text" minlength="8" maxlength="8" name="cep" id="cep" class="form-control form-control-sm">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="endereco">Endereço</label>
							<input type="text" name="endereco" id="endereco" class="form-control form-control-sm">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="bairro">Bairro</label>
							<input type="text" name="bairro" id="bairro" class="form-control form-control-sm">
						</div>
					</div>			
				</div>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="complemento">Complemento</label>
							<input type="text" name="complemento" id="complemento" class="form-control form-control-sm">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="tipo">Tipo</label>
							<select class="form-control form-control-sm"  name="tipo" id="tipo">
								<option value="apartamento">Apartamento</option>
								<option value="casa">Casa</option>
								<option value="ktinet">Ktinet</option>
							</select>
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="cidade">Cidade</label>
							<select class="form-control form-control-sm"  name="cidade" id="cidade">
								<option value="0">São Luís</option>
								<option value="1">Bacuri</option>
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col" align="left">
						<button type="submit" class="btn btn-sm btn-primary">Cadastrar</button>
						<a align='right' href="/" id="cancelar" class="btn btn-sm btn-danger">Cancelar</a>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>