<div class="row" style="background-color: #fff; width: 100%;  margin: auto;" align="left">
	<div class="col py-3">
		<div class="row mb-2"><div class="col" id="msg-cartao"></div></div>
		<div class="row mb-4">
			<div class="col h4" style="width: 80%;" align="center"><strong>Adicionar Cartao</strong></div>
		</div>
		<div class="row">
			<form method="post" id="cadastro-cartao" action="/cartao/salvar" enctype="multipart/form-data" style="margin: auto; width: 80%;">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="numero">Numero cartão</label>
							<input type="text" name="numero" id="numero" class="form-control form-control-sm">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="bandeira">Bandeira cartão</label>
							<input type="text" name="bandeira" id="bandeira" class="form-control form-control-sm">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label>Cvv</label>
							<input type="text"  maxlength="3" id="cvv" class="form-control form-control-sm" name="cvv">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="validade_mes">Mes validade</label>
							<input type="text" maxlength="2" id="validade_mes" class="form-control form-control-sm" name="validade_mes">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label>Ano validade</label>
							<input type="text" maxlength="4" id="ano_validade" class="form-control form-control-sm" name="ano_validade">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="cpf_cartao" >Cpf Cartao</label>
							<input type="text" id="cpf_cartao" class="form-control form-control-sm" name="cpf_cartao">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col" align="left">
						<button id="adicionar" class="btn btn-sm btn-success">Adicionar</button>			
						<a align='right' href="/pessoa/pagamento" id="cancelar" class="btn btn-sm btn-danger">Cancelar</a>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>